/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.mach1.Mach1SpatialLibs;

class Mach1Point3DModuleJNI {
 
  static {
    System.loadLibrary("Mach1Point3DModule_lib");
  }

  public final static native void Mach1Point3D_x_set(long jarg1, Mach1Point3D jarg1_, float jarg2);
  public final static native float Mach1Point3D_x_get(long jarg1, Mach1Point3D jarg1_);
  public final static native void Mach1Point3D_y_set(long jarg1, Mach1Point3D jarg1_, float jarg2);
  public final static native float Mach1Point3D_y_get(long jarg1, Mach1Point3D jarg1_);
  public final static native void Mach1Point3D_z_set(long jarg1, Mach1Point3D jarg1_, float jarg2);
  public final static native float Mach1Point3D_z_get(long jarg1, Mach1Point3D jarg1_);
  public final static native long new_Mach1Point3D();
  public final static native void delete_Mach1Point3D(long jarg1);
  public final static native long new_Mach1Point3DArray(int jarg1);
  public final static native void delete_Mach1Point3DArray(long jarg1);
  public final static native long Mach1Point3DArray_getitem(long jarg1, Mach1Point3DArray jarg1_, int jarg2);
  public final static native void Mach1Point3DArray_setitem(long jarg1, Mach1Point3DArray jarg1_, int jarg2, long jarg3, Mach1Point3D jarg3_);
  public final static native long Mach1Point3DArray_cast(long jarg1, Mach1Point3DArray jarg1_);
  public final static native long Mach1Point3DArray_frompointer(long jarg1, Mach1Point3D jarg1_);
}
