/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.Mach1;

public class Mach1Encode {

  private long M1obj = 0;

  public Mach1Encode()
  {
    M1obj = Mach1EncodeModuleJNI.Mach1EncodeCAPI_create();
  }

  protected void finalize ( ) {
    if(M1obj != 0)  Mach1EncodeModuleJNI.Mach1EncodeCAPI_delete(M1obj);
  }

  public SWIGTYPE_p_void Mach1EncodeCAPI_getPoints() {
    long cPtr = Mach1EncodeModuleJNI.Mach1EncodeCAPI_getPoints(M1obj);
    return (cPtr == 0) ? null : new SWIGTYPE_p_void(cPtr, false);
  }

  public SWIGTYPE_p_void Mach1EncodeCAPI_getGains() {
    long cPtr = Mach1EncodeModuleJNI.Mach1EncodeCAPI_getGains(M1obj);
    return (cPtr == 0) ? null : new SWIGTYPE_p_void(cPtr, false);
  }

  public SWIGTYPE_p_void Mach1EncodeCAPI_getPointsNames() {
    long cPtr = Mach1EncodeModuleJNI.Mach1EncodeCAPI_getPointsNames(M1obj);
    return (cPtr == 0) ? null : new SWIGTYPE_p_void(cPtr, false);
  }

  public SWIGTYPE_p_void Mach1EncodeCAPI_getGainsForInputChannelNamed(String pointName) {
    long cPtr = Mach1EncodeModuleJNI.Mach1EncodeCAPI_getGainsForInputChannelNamed(M1obj, pointName);
    return (cPtr == 0) ? null : new SWIGTYPE_p_void(cPtr, false);
  }

  public void Mach1EncodeCAPI_generatePointResults() {
    Mach1EncodeModuleJNI.Mach1EncodeCAPI_generatePointResults(M1obj);
  }

  public int Mach1EncodeCAPI_getPointsCount() {
    return Mach1EncodeModuleJNI.Mach1EncodeCAPI_getPointsCount(M1obj);
  }

  public SWIGTYPE_p_void Mach1EncodeCAPI_getResultingVolumesDecoded(Mach1DecodeAlgoType decodeType, SWIGTYPE_p_float decodeResult) {
    long cPtr = Mach1EncodeModuleJNI.Mach1EncodeCAPI_getResultingVolumesDecoded(M1obj, decodeType.swigValue(), SWIGTYPE_p_float.getCPtr(decodeResult));
    return (cPtr == 0) ? null : new SWIGTYPE_p_void(cPtr, false);
  }

  public void Mach1EncodeCAPI_setInputMode(Mach1EncodeInputModeType inputMode) {
    Mach1EncodeModuleJNI.Mach1EncodeCAPI_setInputMode(M1obj, inputMode.swigValue());
  }

  public void Mach1EncodeCAPI_setOutputMode(Mach1EncodeOutputModeType outputMode) {
    Mach1EncodeModuleJNI.Mach1EncodeCAPI_setOutputMode(M1obj, outputMode.swigValue());
  }

  public void Mach1EncodeCAPI_setRotation(float rotation) {
    Mach1EncodeModuleJNI.Mach1EncodeCAPI_setRotation(M1obj, rotation);
  }

  public void Mach1EncodeCAPI_setDiverge(float diverge) {
    Mach1EncodeModuleJNI.Mach1EncodeCAPI_setDiverge(M1obj, diverge);
  }

  public void Mach1EncodeCAPI_setPitch(float pitch) {
    Mach1EncodeModuleJNI.Mach1EncodeCAPI_setPitch(M1obj, pitch);
  }

  public void Mach1EncodeCAPI_setStereoRotate(float sRotate) {
    Mach1EncodeModuleJNI.Mach1EncodeCAPI_setStereoRotate(M1obj, sRotate);
  }

  public void Mach1EncodeCAPI_setStereoSpread(float sSpread) {
    Mach1EncodeModuleJNI.Mach1EncodeCAPI_setStereoSpread(M1obj, sSpread);
  }

  public void Mach1EncodeCAPI_setAutoOrbit(boolean autoOrbit) {
    Mach1EncodeModuleJNI.Mach1EncodeCAPI_setAutoOrbit(M1obj, autoOrbit);
  }

  public void Mach1EncodeCAPI_setIsotropicEncode(boolean isotropicEncode) {
    Mach1EncodeModuleJNI.Mach1EncodeCAPI_setIsotropicEncode(M1obj, isotropicEncode);
  }
}
