/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.mach1.spatiallibs;

public final class Mach1TranscodeFormatType {
  public final static Mach1TranscodeFormatType Mach1TranscodeFormatEmpty = new Mach1TranscodeFormatType("Mach1TranscodeFormatEmpty", Mach1TranscodeModuleJNI.Mach1TranscodeFormatEmpty_get());
  public final static Mach1TranscodeFormatType Mach1TranscodeFormatFuMa = new Mach1TranscodeFormatType("Mach1TranscodeFormatFuMa");
  public final static Mach1TranscodeFormatType Mach1TranscodeFormatACNSN3D = new Mach1TranscodeFormatType("Mach1TranscodeFormatACNSN3D");
  public final static Mach1TranscodeFormatType Mach1TranscodeFormatM1Spatial_4 = new Mach1TranscodeFormatType("Mach1TranscodeFormatM1Spatial-4");
  public final static Mach1TranscodeFormatType Mach1TranscodeFormatM1Spatial_4_2 = new Mach1TranscodeFormatType("Mach1TranscodeFormatM1Spatial-4_2");
  public final static Mach1TranscodeFormatType Mach1TranscodeFormatM1HorizonPairs = new Mach1TranscodeFormatType("Mach1TranscodeFormatM1HorizonPairs");
  public final static Mach1TranscodeFormatType Mach1TranscodeFormatM1Spatial_8 = new Mach1TranscodeFormatType("Mach1TranscodeFormatM1Spatial-8");
  public final static Mach1TranscodeFormatType Mach1TranscodeFormatM1Spatial_8_2 = new Mach1TranscodeFormatType("Mach1TranscodeFormatM1Spatial-8_2");
  public final static Mach1TranscodeFormatType Mach1TranscodeFormatM1Spatial_12 = new Mach1TranscodeFormatType("Mach1TranscodeFormatM1Spatial-12");
  public final static Mach1TranscodeFormatType Mach1TranscodeFormatM1Spatial_14 = new Mach1TranscodeFormatType("Mach1TranscodeFormatM1Spatial-14");
  public final static Mach1TranscodeFormatType Mach1TranscodeFormatMono = new Mach1TranscodeFormatType("Mach1TranscodeFormatMono");
  public final static Mach1TranscodeFormatType Mach1TranscodeFormatStereo = new Mach1TranscodeFormatType("Mach1TranscodeFormatStereo");
  public final static Mach1TranscodeFormatType Mach1TranscodeFormatLCR = new Mach1TranscodeFormatType("Mach1TranscodeFormatLCR");
  public final static Mach1TranscodeFormatType Mach1TranscodeFormatFiveOh = new Mach1TranscodeFormatType("Mach1TranscodeFormatFiveOh");
  public final static Mach1TranscodeFormatType Mach1TranscodeFormatFiveOneFilm = new Mach1TranscodeFormatType("Mach1TranscodeFormatFiveOneFilm");
  public final static Mach1TranscodeFormatType Mach1TranscodeFormatFiveOneFilm_Cinema = new Mach1TranscodeFormatType("Mach1TranscodeFormatFiveOneFilm_Cinema");
  public final static Mach1TranscodeFormatType Mach1TranscodeFormatFiveOneSmpte = new Mach1TranscodeFormatType("Mach1TranscodeFormatFiveOneSmpte");
  public final static Mach1TranscodeFormatType Mach1TranscodeFormatFiveOneDts = new Mach1TranscodeFormatType("Mach1TranscodeFormatFiveOneDts");
  public final static Mach1TranscodeFormatType Mach1TranscodeFormatSixOh = new Mach1TranscodeFormatType("Mach1TranscodeFormatSixOh");
  public final static Mach1TranscodeFormatType Mach1TranscodeFormatSevenOnePt = new Mach1TranscodeFormatType("Mach1TranscodeFormatSevenOnePt");
  public final static Mach1TranscodeFormatType Mach1TranscodeFormatSevenOnePt_Cinema = new Mach1TranscodeFormatType("Mach1TranscodeFormatSevenOnePt_Cinema");
  public final static Mach1TranscodeFormatType Mach1TranscodeFormatACNSN3DO2A = new Mach1TranscodeFormatType("Mach1TranscodeFormatACNSN3DO2A");
  public final static Mach1TranscodeFormatType Mach1TranscodeFormatFuMaO2A = new Mach1TranscodeFormatType("Mach1TranscodeFormatFuMaO2A");
  public final static Mach1TranscodeFormatType Mach1TranscodeFormatTBE = new Mach1TranscodeFormatType("Mach1TranscodeFormatTBE");
  public final static Mach1TranscodeFormatType Mach1TranscodeFormatACNSN3DO3A = new Mach1TranscodeFormatType("Mach1TranscodeFormatACNSN3DO3A");
  public final static Mach1TranscodeFormatType Mach1TranscodeFormatFuMaO3A = new Mach1TranscodeFormatType("Mach1TranscodeFormatFuMaO3A");
  public final static Mach1TranscodeFormatType Mach1TranscodeFormatSevenOneSDDS = new Mach1TranscodeFormatType("Mach1TranscodeFormatSevenOneSDDS");
  public final static Mach1TranscodeFormatType Mach1TranscodeFormatSevenZeroSDDS = new Mach1TranscodeFormatType("Mach1TranscodeFormatSevenZeroSDDS");
  public final static Mach1TranscodeFormatType Mach1TranscodeFormatSevenOneTwo = new Mach1TranscodeFormatType("Mach1TranscodeFormatSevenOneTwo");
  public final static Mach1TranscodeFormatType Mach1TranscodeFormatSevenZeroTwo = new Mach1TranscodeFormatType("Mach1TranscodeFormatSevenZeroTwo");
  public final static Mach1TranscodeFormatType Mach1TranscodeFormatNineOne = new Mach1TranscodeFormatType("Mach1TranscodeFormatNineOne");
  public final static Mach1TranscodeFormatType Mach1TranscodeFormatNineZero = new Mach1TranscodeFormatType("Mach1TranscodeFormatNineZero");
  public final static Mach1TranscodeFormatType Mach1TranscodeFormatStereo_Cinema = new Mach1TranscodeFormatType("Mach1TranscodeFormatStereo_Cinema");
  public final static Mach1TranscodeFormatType Mach1TranscodeFormatFiveOneTwo = new Mach1TranscodeFormatType("Mach1TranscodeFormatFiveOneTwo");
  public final static Mach1TranscodeFormatType Mach1TranscodeFormatFiveZeroTwo = new Mach1TranscodeFormatType("Mach1TranscodeFormatFiveZeroTwo");
  public final static Mach1TranscodeFormatType Mach1TranscodeFormatFiveOneFour = new Mach1TranscodeFormatType("Mach1TranscodeFormatFiveOneFour");
  public final static Mach1TranscodeFormatType Mach1TranscodeFormatFiveZeroFour = new Mach1TranscodeFormatType("Mach1TranscodeFormatFiveZeroFour");
  public final static Mach1TranscodeFormatType Mach1TranscodeFormatSevenOneFour = new Mach1TranscodeFormatType("Mach1TranscodeFormatSevenOneFour");
  public final static Mach1TranscodeFormatType Mach1TranscodeFormatSevenZeroFour = new Mach1TranscodeFormatType("Mach1TranscodeFormatSevenZeroFour");
  public final static Mach1TranscodeFormatType Mach1TranscodeFormatSevenZero_Cinema = new Mach1TranscodeFormatType("Mach1TranscodeFormatSevenZero_Cinema");
  public final static Mach1TranscodeFormatType Mach1TranscodeFormatM1SpatialFaces = new Mach1TranscodeFormatType("Mach1TranscodeFormatM1SpatialFaces");
  public final static Mach1TranscodeFormatType Mach1TranscodeFormatNineOneFour = new Mach1TranscodeFormatType("Mach1TranscodeFormatNineOneFour");
  public final static Mach1TranscodeFormatType Mach1TranscodeFormatNineOneSix = new Mach1TranscodeFormatType("Mach1TranscodeFormatNineOneSix");
  public final static Mach1TranscodeFormatType Mach1TranscodeFormatMarcoSixteen = new Mach1TranscodeFormatType("Mach1TranscodeFormatMarcoSixteen");
  public final static Mach1TranscodeFormatType Mach1TranscodeFormatTTPoints = new Mach1TranscodeFormatType("Mach1TranscodeFormatTTPoints");
  public final static Mach1TranscodeFormatType Mach1TranscodeFormatACNSN3DmaxRE1oa = new Mach1TranscodeFormatType("Mach1TranscodeFormatACNSN3DmaxRE1oa");
  public final static Mach1TranscodeFormatType Mach1TranscodeFormatACNSN3DmaxRE2oa = new Mach1TranscodeFormatType("Mach1TranscodeFormatACNSN3DmaxRE2oa");
  public final static Mach1TranscodeFormatType Mach1TranscodeFormatACNSN3DmaxRE3oa = new Mach1TranscodeFormatType("Mach1TranscodeFormatACNSN3DmaxRE3oa");
  public final static Mach1TranscodeFormatType Mach1TranscodeFormatACNSN3DmaxRE4oa = new Mach1TranscodeFormatType("Mach1TranscodeFormatACNSN3DmaxRE4oa");
  public final static Mach1TranscodeFormatType Mach1TranscodeFormatACNSN3DmaxRE5oa = new Mach1TranscodeFormatType("Mach1TranscodeFormatACNSN3DmaxRE5oa");
  public final static Mach1TranscodeFormatType Mach1TranscodeFormatACNSN3DmaxRE6oa = new Mach1TranscodeFormatType("Mach1TranscodeFormatACNSN3DmaxRE6oa");
  public final static Mach1TranscodeFormatType Mach1TranscodeFormatACNSN3DmaxRE7oa = new Mach1TranscodeFormatType("Mach1TranscodeFormatACNSN3DmaxRE7oa");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static Mach1TranscodeFormatType swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + Mach1TranscodeFormatType.class + " with value " + swigValue);
  }

  private Mach1TranscodeFormatType(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private Mach1TranscodeFormatType(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private Mach1TranscodeFormatType(String swigName, Mach1TranscodeFormatType swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static Mach1TranscodeFormatType[] swigValues = { Mach1TranscodeFormatEmpty, Mach1TranscodeFormatM1Spatial_4, Mach1TranscodeFormatM1Spatial_4_2, Mach1TranscodeFormatM1HorizonPairs, Mach1TranscodeFormatM1Spatial_8, Mach1TranscodeFormatM1Spatial_8_2, Mach1TranscodeFormatM1Spatial_12, Mach1TranscodeFormatM1Spatial_14, Mach1TranscodeFormatFuMa, Mach1TranscodeFormatACNSN3D, Mach1TranscodeFormatMono, Mach1TranscodeFormatStereo, Mach1TranscodeFormatLCR, Mach1TranscodeFormatFiveOh, Mach1TranscodeFormatFiveOneFilm, Mach1TranscodeFormatFiveOneFilm_Cinema, Mach1TranscodeFormatFiveOneSmpte, Mach1TranscodeFormatFiveOneDts, Mach1TranscodeFormatSixOh, Mach1TranscodeFormatSevenOnePt, Mach1TranscodeFormatSevenOnePt_Cinema, Mach1TranscodeFormatACNSN3DO2A, Mach1TranscodeFormatFuMaO2A, Mach1TranscodeFormatTBE, Mach1TranscodeFormatACNSN3DO3A, Mach1TranscodeFormatFuMaO3A, Mach1TranscodeFormatSevenOneSDDS, Mach1TranscodeFormatSevenZeroSDDS, Mach1TranscodeFormatSevenOneTwo, Mach1TranscodeFormatSevenZeroTwo, Mach1TranscodeFormatNineOne, Mach1TranscodeFormatNineZero, Mach1TranscodeFormatStereo_Cinema, Mach1TranscodeFormatFiveOneTwo, Mach1TranscodeFormatFiveZeroTwo, Mach1TranscodeFormatFiveOneFour, Mach1TranscodeFormatFiveZeroFour, Mach1TranscodeFormatSevenOneFour, Mach1TranscodeFormatSevenZeroFour, Mach1TranscodeFormatSevenZero_Cinema, Mach1TranscodeFormatM1SpatialFaces, Mach1TranscodeFormatNineOneFour, Mach1TranscodeFormatNineOneSix, Mach1TranscodeFormatMarcoSixteen, Mach1TranscodeFormatTTPoints, Mach1TranscodeFormatACNSN3DmaxRE1oa, Mach1TranscodeFormatACNSN3DmaxRE2oa, Mach1TranscodeFormatACNSN3DmaxRE3oa, Mach1TranscodeFormatACNSN3DmaxRE4oa, Mach1TranscodeFormatACNSN3DmaxRE5oa, Mach1TranscodeFormatACNSN3DmaxRE6oa, Mach1TranscodeFormatACNSN3DmaxRE7oa };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

