/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.mach1.spatiallibs;

public final class Mach1EncodePannerModeType {
  public final static Mach1EncodePannerModeType Mach1EncodePannerModeIsotropicLinear = new Mach1EncodePannerModeType("Mach1EncodePannerModeIsotropicLinear", Mach1EncodeModuleJNI.Mach1EncodePannerModeIsotropicLinear_get());
  public final static Mach1EncodePannerModeType Mach1EncodePannerModeIsotropicEqualPower = new Mach1EncodePannerModeType("Mach1EncodePannerModeIsotropicEqualPower");
  public final static Mach1EncodePannerModeType Mach1EncodePannerModePeriphonicLinear = new Mach1EncodePannerModeType("Mach1EncodePannerModePeriphonicLinear");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static Mach1EncodePannerModeType swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + Mach1EncodePannerModeType.class + " with value " + swigValue);
  }

  private Mach1EncodePannerModeType(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private Mach1EncodePannerModeType(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private Mach1EncodePannerModeType(String swigName, Mach1EncodePannerModeType swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static Mach1EncodePannerModeType[] swigValues = { Mach1EncodePannerModeIsotropicLinear, Mach1EncodePannerModeIsotropicEqualPower, Mach1EncodePannerModePeriphonicLinear };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

