/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.mach1.spatiallibs;

public final class Mach1EncodeOutputModeType {
  public final static Mach1EncodeOutputModeType Mach1EncodeOutputModeM1Spatial_8 = new Mach1EncodeOutputModeType("Mach1EncodeOutputModeM1Spatial_8", Mach1EncodeModuleJNI.Mach1EncodeOutputModeM1Spatial_8_get());
  public final static Mach1EncodeOutputModeType Mach1EncodeOutputModeM1Horizon_4 = new Mach1EncodeOutputModeType("Mach1EncodeOutputModeM1Horizon_4");
  public final static Mach1EncodeOutputModeType Mach1EncodeOutputModeM1Spatial_12 = new Mach1EncodeOutputModeType("Mach1EncodeOutputModeM1Spatial_12");
  public final static Mach1EncodeOutputModeType Mach1EncodeOutputModeM1Spatial_14 = new Mach1EncodeOutputModeType("Mach1EncodeOutputModeM1Spatial_14");
  public final static Mach1EncodeOutputModeType Mach1EncodeOutputModeM1Spatial_18 = new Mach1EncodeOutputModeType("Mach1EncodeOutputModeM1Spatial_18");
  public final static Mach1EncodeOutputModeType Mach1EncodeOutputModeM1Spatial_22 = new Mach1EncodeOutputModeType("Mach1EncodeOutputModeM1Spatial_22");
  public final static Mach1EncodeOutputModeType Mach1EncodeOutputModeM1Spatial_32 = new Mach1EncodeOutputModeType("Mach1EncodeOutputModeM1Spatial_32");
  public final static Mach1EncodeOutputModeType Mach1EncodeOutputModeM1Spatial_36 = new Mach1EncodeOutputModeType("Mach1EncodeOutputModeM1Spatial_36");
  public final static Mach1EncodeOutputModeType Mach1EncodeOutputModeM1Spatial_48 = new Mach1EncodeOutputModeType("Mach1EncodeOutputModeM1Spatial_48");
  public final static Mach1EncodeOutputModeType Mach1EncodeOutputModeM1Spatial_60 = new Mach1EncodeOutputModeType("Mach1EncodeOutputModeM1Spatial_60");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static Mach1EncodeOutputModeType swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + Mach1EncodeOutputModeType.class + " with value " + swigValue);
  }

  private Mach1EncodeOutputModeType(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private Mach1EncodeOutputModeType(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private Mach1EncodeOutputModeType(String swigName, Mach1EncodeOutputModeType swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static Mach1EncodeOutputModeType[] swigValues = { Mach1EncodeOutputModeM1Spatial_8, Mach1EncodeOutputModeM1Horizon_4, Mach1EncodeOutputModeM1Spatial_12, Mach1EncodeOutputModeM1Spatial_14, Mach1EncodeOutputModeM1Spatial_18, Mach1EncodeOutputModeM1Spatial_22, Mach1EncodeOutputModeM1Spatial_32, Mach1EncodeOutputModeM1Spatial_36, Mach1EncodeOutputModeM1Spatial_48, Mach1EncodeOutputModeM1Spatial_60 };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

