/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.2.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.mach1.spatiallibs;

public final class Mach1DecodeMode {
  public final static Mach1DecodeMode M1DecodeSpatial_4 = new Mach1DecodeMode("M1DecodeSpatial_4", Mach1DecodeModuleJNI.M1DecodeSpatial_4_get());
  public final static Mach1DecodeMode M1DecodeSpatial_8 = new Mach1DecodeMode("M1DecodeSpatial_8");
  public final static Mach1DecodeMode M1DecodeSpatial_12 = new Mach1DecodeMode("M1DecodeSpatial_12");
  public final static Mach1DecodeMode M1DecodeSpatial_14 = new Mach1DecodeMode("M1DecodeSpatial_14");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static Mach1DecodeMode swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + Mach1DecodeMode.class + " with value " + swigValue);
  }

  private Mach1DecodeMode(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private Mach1DecodeMode(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private Mach1DecodeMode(String swigName, Mach1DecodeMode swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static Mach1DecodeMode[] swigValues = { M1DecodeSpatial_4, M1DecodeSpatial_8, M1DecodeSpatial_12, M1DecodeSpatial_14 };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}
