/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.2.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.mach1.spatiallibs;

class Mach1DecodeModuleJNI {

  static {
    System.loadLibrary("Mach1DecodeModule_lib");
  }

  public final static native int Mach1PlatformDefault_get();
  public final static native int M1DecodeSpatial_4_get();
  public final static native long Mach1DecodeCAPI_create();
  public final static native void Mach1DecodeCAPI_delete(long jarg1);
  public final static native void Mach1DecodeCAPI_setDecodeMode(long jarg1, int jarg2);
  public final static native void Mach1DecodeCAPI_setPlatformType(long jarg1, int jarg2);
  public final static native int Mach1DecodeCAPI_getDecodeMode(long jarg1);
  public final static native int Mach1DecodeCAPI_getPlatformType(long jarg1);
  public final static native void Mach1DecodeCAPI_decode(long jarg1, float jarg2, float jarg3, float jarg4, long jarg5, int jarg6, int jarg7);
  public final static native void Mach1DecodeCAPI_decodeCoeffs(long jarg1, long jarg2, int jarg3, int jarg4);
  public final static native void Mach1DecodeCAPI_decodePannedCoeffs(long jarg1, long jarg2, int jarg3, int jarg4, boolean jarg5);
  public final static native void Mach1DecodeCAPI_decodeCoeffsUsingTranscodeMatrix(long jarg1, long jarg2, int jarg3, long jarg4, int jarg5, int jarg6);
  public final static native void Mach1DecodeCAPI_setFilterSpeed(long jarg1, float jarg2);
  public final static native int Mach1DecodeCAPI_getFormatChannelCount(long jarg1);
  public final static native int Mach1DecodeCAPI_getFormatCoeffCount(long jarg1);
  public final static native void Mach1DecodeCAPI_setRotation(long jarg1, long jarg2, Mach1Point3D jarg2_);
  public final static native void Mach1DecodeCAPI_setRotationDegrees(long jarg1, long jarg2, Mach1Point3D jarg2_);
  public final static native void Mach1DecodeCAPI_setRotationRadians(long jarg1, long jarg2, Mach1Point3D jarg2_);
  public final static native void Mach1DecodeCAPI_setRotationQuat(long jarg1, long jarg2, Mach1Point4D jarg2_);
  public final static native int Mach1DecodeCAPI_getCurrentTime(long jarg1);
  public final static native int Mach1DecodeCAPI_getLastCalculationTime(long jarg1);
  public final static native String Mach1DecodeCAPI_getLog(long jarg1);
  public final static native long Mach1DecodeCAPI_getCurrentAngle(long jarg1);
}
