/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.2.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.mach1.spatiallibs;

public final class Mach1EncodeInputMode {
  public final static Mach1EncodeInputMode Mono = new Mach1EncodeInputMode("Mono", Mach1EncodeModuleJNI.Mono_get());
  public final static Mach1EncodeInputMode Stereo = new Mach1EncodeInputMode("Stereo");
  public final static Mach1EncodeInputMode LCR = new Mach1EncodeInputMode("LCR");
  public final static Mach1EncodeInputMode Quad = new Mach1EncodeInputMode("Quad");
  public final static Mach1EncodeInputMode LCRS = new Mach1EncodeInputMode("LCRS");
  public final static Mach1EncodeInputMode AFormat = new Mach1EncodeInputMode("AFormat");
  public final static Mach1EncodeInputMode FiveDotZero = new Mach1EncodeInputMode("FiveDotZero");
  public final static Mach1EncodeInputMode FiveDotOneFilm = new Mach1EncodeInputMode("FiveDotOneFilm");
  public final static Mach1EncodeInputMode FiveDotOneDTS = new Mach1EncodeInputMode("FiveDotOneDTS");
  public final static Mach1EncodeInputMode FiveDotOneSMTPE = new Mach1EncodeInputMode("FiveDotOneSMTPE");
  public final static Mach1EncodeInputMode BFOAACN = new Mach1EncodeInputMode("BFOAACN");
  public final static Mach1EncodeInputMode BFOAFUMA = new Mach1EncodeInputMode("BFOAFUMA");
  public final static Mach1EncodeInputMode B2OAACN = new Mach1EncodeInputMode("B2OAACN");
  public final static Mach1EncodeInputMode B2OAFUMA = new Mach1EncodeInputMode("B2OAFUMA");
  public final static Mach1EncodeInputMode B3OAACN = new Mach1EncodeInputMode("B3OAACN");
  public final static Mach1EncodeInputMode B3OAFUMA = new Mach1EncodeInputMode("B3OAFUMA");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static Mach1EncodeInputMode swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + Mach1EncodeInputMode.class + " with value " + swigValue);
  }

  private Mach1EncodeInputMode(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private Mach1EncodeInputMode(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private Mach1EncodeInputMode(String swigName, Mach1EncodeInputMode swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static Mach1EncodeInputMode[] swigValues = { Mono, Stereo, LCR, Quad, LCRS, AFormat, FiveDotZero, FiveDotOneFilm, FiveDotOneDTS, FiveDotOneSMTPE, BFOAACN, BFOAFUMA, B2OAACN, B2OAFUMA, B3OAACN, B3OAFUMA };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}
