/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.2.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.mach1.spatiallibs;

public final class Mach1EncodeOutputMode {
  public final static Mach1EncodeOutputMode M1Spatial_4 = new Mach1EncodeOutputMode("M1Spatial_4", Mach1EncodeModuleJNI.M1Spatial_4_get());
  public final static Mach1EncodeOutputMode M1Spatial_8 = new Mach1EncodeOutputMode("M1Spatial_8");
  public final static Mach1EncodeOutputMode M1Spatial_14 = new Mach1EncodeOutputMode("M1Spatial_14");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static Mach1EncodeOutputMode swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + Mach1EncodeOutputMode.class + " with value " + swigValue);
  }

  private Mach1EncodeOutputMode(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private Mach1EncodeOutputMode(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private Mach1EncodeOutputMode(String swigName, Mach1EncodeOutputMode swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static Mach1EncodeOutputMode[] swigValues = { M1Spatial_4, M1Spatial_8, M1Spatial_14 };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

