/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.2.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.mach1.spatiallibs;

public final class Mach1DecodeAlgoType {
  public final static Mach1DecodeAlgoType Mach1DecodeAlgoSpatial_4 = new Mach1DecodeAlgoType("Mach1DecodeAlgoSpatial_4", Mach1DecodeModuleJNI.Mach1DecodeAlgoSpatial_4_get());
  public final static Mach1DecodeAlgoType Mach1DecodeAlgoSpatial_8 = new Mach1DecodeAlgoType("Mach1DecodeAlgoSpatial_8");
  public final static Mach1DecodeAlgoType Mach1DecodeAlgoSpatial_12 = new Mach1DecodeAlgoType("Mach1DecodeAlgoSpatial_12");
  public final static Mach1DecodeAlgoType Mach1DecodeAlgoSpatial_14 = new Mach1DecodeAlgoType("Mach1DecodeAlgoSpatial_14");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static Mach1DecodeAlgoType swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + Mach1DecodeAlgoType.class + " with value " + swigValue);
  }

  private Mach1DecodeAlgoType(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private Mach1DecodeAlgoType(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private Mach1DecodeAlgoType(String swigName, Mach1DecodeAlgoType swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static Mach1DecodeAlgoType[] swigValues = { Mach1DecodeAlgoSpatial_4, Mach1DecodeAlgoSpatial_8, Mach1DecodeAlgoSpatial_12, Mach1DecodeAlgoSpatial_14 };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

