/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.2.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.mach1.spatiallibs;

public final class Mach1EncodePannerMode {
  public final static Mach1EncodePannerMode IsotropicLinear = new Mach1EncodePannerMode("IsotropicLinear", Mach1EncodeModuleJNI.IsotropicLinear_get());
  public final static Mach1EncodePannerMode IsotropicEqualPower = new Mach1EncodePannerMode("IsotropicEqualPower");
  public final static Mach1EncodePannerMode PeriphonicLinear = new Mach1EncodePannerMode("PeriphonicLinear");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static Mach1EncodePannerMode swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + Mach1EncodePannerMode.class + " with value " + swigValue);
  }

  private Mach1EncodePannerMode(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private Mach1EncodePannerMode(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private Mach1EncodePannerMode(String swigName, Mach1EncodePannerMode swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static Mach1EncodePannerMode[] swigValues = { IsotropicLinear, IsotropicEqualPower, PeriphonicLinear };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}
