/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.2.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.mach1.spatiallibs;

public class SWIGTYPE_p_f_long_long_r_int__p_Mach1Point3D {
  private transient long swigCPtr;

  protected SWIGTYPE_p_f_long_long_r_int__p_Mach1Point3D(long cPtr, @SuppressWarnings("unused") boolean futureUse) {
    swigCPtr = cPtr;
  }

  protected SWIGTYPE_p_f_long_long_r_int__p_Mach1Point3D() {
    swigCPtr = 0;
  }

  protected static long getCPtr(SWIGTYPE_p_f_long_long_r_int__p_Mach1Point3D obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(SWIGTYPE_p_f_long_long_r_int__p_Mach1Point3D obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }
}

