/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.mach1.spatiallibs;

class Mach1UtilsModuleJNI {
  public final static native String convertToString(long jarg1);
  public final static native long getitemVoid(long jarg1, int jarg2);
 
  static {
    System.loadLibrary("Mach1UtilsModule_lib");
  }

}
