/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.mach1.spatiallibs;

public class Mach1Decode {

  private long M1obj = 0;

  public Mach1Decode()
  {
    M1obj = Mach1DecodeModuleJNI.Mach1DecodeCAPI_create();
  }

  protected void finalize ( ) {
    if(M1obj != 0) Mach1DecodeModuleJNI.Mach1DecodeCAPI_delete(M1obj);
  }

  public void setDecodeAlgoType(Mach1DecodeAlgoType algorithmType)
  {
    Mach1DecodeModuleJNI.Mach1DecodeCAPI_setDecodeAlgoType(M1obj, algorithmType.swigValue());
  }

  public void setPlatformType(Mach1PlatformType platformType)
  {
    Mach1DecodeModuleJNI.Mach1DecodeCAPI_setPlatformType(M1obj, platformType.swigValue());
  }

  public void setFilterSpeed(float filterSpeed)
  {
    Mach1DecodeModuleJNI.Mach1DecodeCAPI_setFilterSpeed(M1obj, filterSpeed);
  }

  public void setRotation(Mach1Point3D newRotationFromMinusOnetoOne)
  {
    Mach1DecodeModuleJNI.Mach1DecodeCAPI_setRotation(M1obj, Mach1Point3D.getCPtr(newRotationFromMinusOnetoOne), newRotationFromMinusOnetoOne);
  }

  public void setRotationDegrees(Mach1Point3D newRotationDegrees)
  {
    Mach1DecodeModuleJNI.Mach1DecodeCAPI_setRotationDegrees(M1obj, Mach1Point3D.getCPtr(newRotationDegrees), newRotationDegrees);
  }

  public void setRotationRadians(Mach1Point3D newRotationRadians)
  {
    Mach1DecodeModuleJNI.Mach1DecodeCAPI_setRotationRadians(M1obj, Mach1Point3D.getCPtr(newRotationRadians), newRotationRadians);
  }

  public void setRotationQuat(Mach1Point4D newRotationQuat)
  {
    Mach1DecodeModuleJNI.Mach1DecodeCAPI_setRotationQuat(M1obj, Mach1Point4D.getCPtr(newRotationQuat), newRotationQuat);
  }

  public void decode(float Yaw, float Pitch, float Roll, float[] data, int bufferSize, int sampleIndex)
  {
    int cnt = 18;
    Mach1FloatArray arr = new Mach1FloatArray(cnt);
    Mach1DecodeModuleJNI.Mach1DecodeCAPI_decode(M1obj, Yaw, Pitch, Roll, SWIGTYPE_p_float.getCPtr(arr.cast()), bufferSize, sampleIndex);

    for(int i=0; i<cnt; i++) {
      data[i] = arr.getitem(i);
    }
    arr.delete();
  }

  public void decodeCoeffs(float[] data, int bufferSize, int sampleIndex)
  {
    int cnt = 18;
    Mach1FloatArray arr = new Mach1FloatArray(cnt);
    Mach1DecodeModuleJNI.Mach1DecodeCAPI_decodeCoeffs(M1obj, SWIGTYPE_p_float.getCPtr(arr.cast()), bufferSize, sampleIndex);

    for(int i=0; i<cnt; i++) {
      data[i] = arr.getitem(i);
    }
    arr.delete();
  }

  public void beginBuffer()
  {
    Mach1DecodeModuleJNI.Mach1DecodeCAPI_beginBuffer(M1obj);
  }

  public void endBuffer()
  {
    Mach1DecodeModuleJNI.Mach1DecodeCAPI_endBuffer(M1obj);
  }

  public int getFormatChannelCount()
  {
    return Mach1DecodeModuleJNI.Mach1DecodeCAPI_getFormatChannelCount(M1obj);
  }

  public int getDecodeAlgoType()
  {
    return Mach1DecodeModuleJNI.Mach1DecodeCAPI_getDecodeAlgoType(M1obj);
  }

  public int getPlatformType()
  {
    return Mach1DecodeModuleJNI.Mach1DecodeCAPI_getPlatformType(M1obj);
  }

  public Mach1Point3D getCurrentAngle()
  {
    return new Mach1Point3D(Mach1DecodeModuleJNI.Mach1DecodeCAPI_getCurrentAngle(M1obj), true);
  }

  public long getCurrentTime()
  {
    return Mach1DecodeModuleJNI.Mach1DecodeCAPI_getCurrentTime(M1obj);
  }

  public String getLog()
  {
    return Mach1DecodeModuleJNI.Mach1DecodeCAPI_getLog(M1obj);
  }

}
