# Install script for directory: /Volumes/git/m1-sdk/lib

# Set the install prefix
if(NOT DEFINED CMAKE_INSTALL_PREFIX)
  set(CMAKE_INSTALL_PREFIX "/Volumes/git/m1-sdk/lib/_install/ios")
endif()
string(REGEX REPLACE "/$" "" CMAKE_INSTALL_PREFIX "${CMAKE_INSTALL_PREFIX}")

# Set the install configuration name.
if(NOT DEFINED CMAKE_INSTALL_CONFIG_NAME)
  if(BUILD_TYPE)
    string(REGEX REPLACE "^[^A-Za-z0-9_]+" ""
           CMAKE_INSTALL_CONFIG_NAME "${BUILD_TYPE}")
  else()
    set(CMAKE_INSTALL_CONFIG_NAME "Release")
  endif()
  message(STATUS "Install configuration: \"${CMAKE_INSTALL_CONFIG_NAME}\"")
endif()

# Set the component getting installed.
if(NOT CMAKE_INSTALL_COMPONENT)
  if(COMPONENT)
    message(STATUS "Install component: \"${COMPONENT}\"")
    set(CMAKE_INSTALL_COMPONENT "${COMPONENT}")
  else()
    set(CMAKE_INSTALL_COMPONENT)
  endif()
endif()

# Is this installation the result of a crosscompile?
if(NOT DEFINED CMAKE_CROSSCOMPILING)
  set(CMAKE_CROSSCOMPILING "TRUE")
endif()

# Set default install directory permissions.
if(NOT DEFINED CMAKE_OBJDUMP)
  set(CMAKE_OBJDUMP "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/objdump")
endif()

set(CMAKE_BINARY_DIR "/Volumes/git/m1-sdk/lib/_builds/ios")

if(NOT PLATFORM_NAME)
  if(NOT "$ENV{PLATFORM_NAME}" STREQUAL "")
    set(PLATFORM_NAME "$ENV{PLATFORM_NAME}")
  endif()
  if(NOT PLATFORM_NAME)
    set(PLATFORM_NAME iphoneos)
  endif()
endif()

if(NOT EFFECTIVE_PLATFORM_NAME)
  if(NOT "$ENV{EFFECTIVE_PLATFORM_NAME}" STREQUAL "")
    set(EFFECTIVE_PLATFORM_NAME "$ENV{EFFECTIVE_PLATFORM_NAME}")
  endif()
  if(NOT EFFECTIVE_PLATFORM_NAME)
    set(EFFECTIVE_PLATFORM_NAME -iphoneos)
  endif()
endif()

if("x${CMAKE_INSTALL_COMPONENT}x" STREQUAL "xUnspecifiedx" OR NOT CMAKE_INSTALL_COMPONENT)
  if("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/lib" TYPE STATIC_LIBRARY FILES "/Volumes/git/m1-sdk/lib/_builds/ios/static/Debug/libMach1DecodeCAPId.a")
    if(EXISTS "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/lib/libMach1DecodeCAPId.a" AND
       NOT IS_SYMLINK "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/lib/libMach1DecodeCAPId.a")
      include(CMakeIOSInstallCombined)
      ios_install_combined("Mach1DecodeCAPIstatic" "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/lib/libMach1DecodeCAPId.a")
      execute_process(COMMAND "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib" "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/lib/libMach1DecodeCAPId.a")
    endif()
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/lib" TYPE STATIC_LIBRARY FILES "/Volumes/git/m1-sdk/lib/_builds/ios/static/Release/libMach1DecodeCAPI.a")
    if(EXISTS "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/lib/libMach1DecodeCAPI.a" AND
       NOT IS_SYMLINK "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/lib/libMach1DecodeCAPI.a")
      include(CMakeIOSInstallCombined)
      ios_install_combined("Mach1DecodeCAPIstatic" "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/lib/libMach1DecodeCAPI.a")
      execute_process(COMMAND "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib" "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/lib/libMach1DecodeCAPI.a")
    endif()
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/lib" TYPE STATIC_LIBRARY FILES "/Volumes/git/m1-sdk/lib/_builds/ios/static/MinSizeRel/libMach1DecodeCAPI.a")
    if(EXISTS "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/lib/libMach1DecodeCAPI.a" AND
       NOT IS_SYMLINK "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/lib/libMach1DecodeCAPI.a")
      include(CMakeIOSInstallCombined)
      ios_install_combined("Mach1DecodeCAPIstatic" "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/lib/libMach1DecodeCAPI.a")
      execute_process(COMMAND "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib" "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/lib/libMach1DecodeCAPI.a")
    endif()
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/lib" TYPE STATIC_LIBRARY FILES "/Volumes/git/m1-sdk/lib/_builds/ios/static/RelWithDebInfo/libMach1DecodeCAPI.a")
    if(EXISTS "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/lib/libMach1DecodeCAPI.a" AND
       NOT IS_SYMLINK "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/lib/libMach1DecodeCAPI.a")
      include(CMakeIOSInstallCombined)
      ios_install_combined("Mach1DecodeCAPIstatic" "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/lib/libMach1DecodeCAPI.a")
      execute_process(COMMAND "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib" "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/lib/libMach1DecodeCAPI.a")
    endif()
  endif()
endif()

if("x${CMAKE_INSTALL_COMPONENT}x" STREQUAL "xUnspecifiedx" OR NOT CMAKE_INSTALL_COMPONENT)
  if("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/lib" TYPE STATIC_LIBRARY FILES "/Volumes/git/m1-sdk/lib/_builds/ios/static/Debug/libMach1DecodePositionalCAPId.a")
    if(EXISTS "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/lib/libMach1DecodePositionalCAPId.a" AND
       NOT IS_SYMLINK "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/lib/libMach1DecodePositionalCAPId.a")
      include(CMakeIOSInstallCombined)
      ios_install_combined("Mach1DecodePositionalCAPIstatic" "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/lib/libMach1DecodePositionalCAPId.a")
      execute_process(COMMAND "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib" "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/lib/libMach1DecodePositionalCAPId.a")
    endif()
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/lib" TYPE STATIC_LIBRARY FILES "/Volumes/git/m1-sdk/lib/_builds/ios/static/Release/libMach1DecodePositionalCAPI.a")
    if(EXISTS "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/lib/libMach1DecodePositionalCAPI.a" AND
       NOT IS_SYMLINK "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/lib/libMach1DecodePositionalCAPI.a")
      include(CMakeIOSInstallCombined)
      ios_install_combined("Mach1DecodePositionalCAPIstatic" "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/lib/libMach1DecodePositionalCAPI.a")
      execute_process(COMMAND "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib" "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/lib/libMach1DecodePositionalCAPI.a")
    endif()
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/lib" TYPE STATIC_LIBRARY FILES "/Volumes/git/m1-sdk/lib/_builds/ios/static/MinSizeRel/libMach1DecodePositionalCAPI.a")
    if(EXISTS "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/lib/libMach1DecodePositionalCAPI.a" AND
       NOT IS_SYMLINK "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/lib/libMach1DecodePositionalCAPI.a")
      include(CMakeIOSInstallCombined)
      ios_install_combined("Mach1DecodePositionalCAPIstatic" "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/lib/libMach1DecodePositionalCAPI.a")
      execute_process(COMMAND "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib" "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/lib/libMach1DecodePositionalCAPI.a")
    endif()
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/lib" TYPE STATIC_LIBRARY FILES "/Volumes/git/m1-sdk/lib/_builds/ios/static/RelWithDebInfo/libMach1DecodePositionalCAPI.a")
    if(EXISTS "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/lib/libMach1DecodePositionalCAPI.a" AND
       NOT IS_SYMLINK "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/lib/libMach1DecodePositionalCAPI.a")
      include(CMakeIOSInstallCombined)
      ios_install_combined("Mach1DecodePositionalCAPIstatic" "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/lib/libMach1DecodePositionalCAPI.a")
      execute_process(COMMAND "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib" "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/lib/libMach1DecodePositionalCAPI.a")
    endif()
  endif()
endif()

if("x${CMAKE_INSTALL_COMPONENT}x" STREQUAL "xUnspecifiedx" OR NOT CMAKE_INSTALL_COMPONENT)
  if("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/lib" TYPE STATIC_LIBRARY FILES "/Volumes/git/m1-sdk/lib/_builds/ios/static/Debug/libMach1EncodeCAPId.a")
    if(EXISTS "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/lib/libMach1EncodeCAPId.a" AND
       NOT IS_SYMLINK "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/lib/libMach1EncodeCAPId.a")
      include(CMakeIOSInstallCombined)
      ios_install_combined("Mach1EncodeCAPIstatic" "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/lib/libMach1EncodeCAPId.a")
      execute_process(COMMAND "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib" "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/lib/libMach1EncodeCAPId.a")
    endif()
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/lib" TYPE STATIC_LIBRARY FILES "/Volumes/git/m1-sdk/lib/_builds/ios/static/Release/libMach1EncodeCAPI.a")
    if(EXISTS "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/lib/libMach1EncodeCAPI.a" AND
       NOT IS_SYMLINK "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/lib/libMach1EncodeCAPI.a")
      include(CMakeIOSInstallCombined)
      ios_install_combined("Mach1EncodeCAPIstatic" "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/lib/libMach1EncodeCAPI.a")
      execute_process(COMMAND "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib" "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/lib/libMach1EncodeCAPI.a")
    endif()
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/lib" TYPE STATIC_LIBRARY FILES "/Volumes/git/m1-sdk/lib/_builds/ios/static/MinSizeRel/libMach1EncodeCAPI.a")
    if(EXISTS "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/lib/libMach1EncodeCAPI.a" AND
       NOT IS_SYMLINK "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/lib/libMach1EncodeCAPI.a")
      include(CMakeIOSInstallCombined)
      ios_install_combined("Mach1EncodeCAPIstatic" "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/lib/libMach1EncodeCAPI.a")
      execute_process(COMMAND "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib" "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/lib/libMach1EncodeCAPI.a")
    endif()
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/lib" TYPE STATIC_LIBRARY FILES "/Volumes/git/m1-sdk/lib/_builds/ios/static/RelWithDebInfo/libMach1EncodeCAPI.a")
    if(EXISTS "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/lib/libMach1EncodeCAPI.a" AND
       NOT IS_SYMLINK "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/lib/libMach1EncodeCAPI.a")
      include(CMakeIOSInstallCombined)
      ios_install_combined("Mach1EncodeCAPIstatic" "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/lib/libMach1EncodeCAPI.a")
      execute_process(COMMAND "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib" "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/lib/libMach1EncodeCAPI.a")
    endif()
  endif()
endif()

if("x${CMAKE_INSTALL_COMPONENT}x" STREQUAL "xUnspecifiedx" OR NOT CMAKE_INSTALL_COMPONENT)
  if("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/lib" TYPE STATIC_LIBRARY FILES "/Volumes/git/m1-sdk/lib/_builds/ios/static/Debug/libMach1TranscodeCAPId.a")
    if(EXISTS "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/lib/libMach1TranscodeCAPId.a" AND
       NOT IS_SYMLINK "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/lib/libMach1TranscodeCAPId.a")
      include(CMakeIOSInstallCombined)
      ios_install_combined("Mach1TranscodeCAPIstatic" "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/lib/libMach1TranscodeCAPId.a")
      execute_process(COMMAND "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib" "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/lib/libMach1TranscodeCAPId.a")
    endif()
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/lib" TYPE STATIC_LIBRARY FILES "/Volumes/git/m1-sdk/lib/_builds/ios/static/Release/libMach1TranscodeCAPI.a")
    if(EXISTS "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/lib/libMach1TranscodeCAPI.a" AND
       NOT IS_SYMLINK "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/lib/libMach1TranscodeCAPI.a")
      include(CMakeIOSInstallCombined)
      ios_install_combined("Mach1TranscodeCAPIstatic" "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/lib/libMach1TranscodeCAPI.a")
      execute_process(COMMAND "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib" "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/lib/libMach1TranscodeCAPI.a")
    endif()
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/lib" TYPE STATIC_LIBRARY FILES "/Volumes/git/m1-sdk/lib/_builds/ios/static/MinSizeRel/libMach1TranscodeCAPI.a")
    if(EXISTS "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/lib/libMach1TranscodeCAPI.a" AND
       NOT IS_SYMLINK "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/lib/libMach1TranscodeCAPI.a")
      include(CMakeIOSInstallCombined)
      ios_install_combined("Mach1TranscodeCAPIstatic" "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/lib/libMach1TranscodeCAPI.a")
      execute_process(COMMAND "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib" "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/lib/libMach1TranscodeCAPI.a")
    endif()
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/lib" TYPE STATIC_LIBRARY FILES "/Volumes/git/m1-sdk/lib/_builds/ios/static/RelWithDebInfo/libMach1TranscodeCAPI.a")
    if(EXISTS "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/lib/libMach1TranscodeCAPI.a" AND
       NOT IS_SYMLINK "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/lib/libMach1TranscodeCAPI.a")
      include(CMakeIOSInstallCombined)
      ios_install_combined("Mach1TranscodeCAPIstatic" "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/lib/libMach1TranscodeCAPI.a")
      execute_process(COMMAND "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib" "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/lib/libMach1TranscodeCAPI.a")
    endif()
  endif()
endif()

if("x${CMAKE_INSTALL_COMPONENT}x" STREQUAL "xUnspecifiedx" OR NOT CMAKE_INSTALL_COMPONENT)
  if("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/lib" TYPE STATIC_LIBRARY FILES "/Volumes/git/m1-sdk/lib/_builds/ios/static/Debug/libMach1Decode-minifiedCAPId.a")
    if(EXISTS "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/lib/libMach1Decode-minifiedCAPId.a" AND
       NOT IS_SYMLINK "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/lib/libMach1Decode-minifiedCAPId.a")
      include(CMakeIOSInstallCombined)
      ios_install_combined("Mach1DecodeMINCAPIstatic" "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/lib/libMach1Decode-minifiedCAPId.a")
      execute_process(COMMAND "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib" "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/lib/libMach1Decode-minifiedCAPId.a")
    endif()
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/lib" TYPE STATIC_LIBRARY FILES "/Volumes/git/m1-sdk/lib/_builds/ios/static/Release/libMach1Decode-minifiedCAPI.a")
    if(EXISTS "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/lib/libMach1Decode-minifiedCAPI.a" AND
       NOT IS_SYMLINK "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/lib/libMach1Decode-minifiedCAPI.a")
      include(CMakeIOSInstallCombined)
      ios_install_combined("Mach1DecodeMINCAPIstatic" "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/lib/libMach1Decode-minifiedCAPI.a")
      execute_process(COMMAND "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib" "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/lib/libMach1Decode-minifiedCAPI.a")
    endif()
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/lib" TYPE STATIC_LIBRARY FILES "/Volumes/git/m1-sdk/lib/_builds/ios/static/MinSizeRel/libMach1Decode-minifiedCAPI.a")
    if(EXISTS "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/lib/libMach1Decode-minifiedCAPI.a" AND
       NOT IS_SYMLINK "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/lib/libMach1Decode-minifiedCAPI.a")
      include(CMakeIOSInstallCombined)
      ios_install_combined("Mach1DecodeMINCAPIstatic" "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/lib/libMach1Decode-minifiedCAPI.a")
      execute_process(COMMAND "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib" "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/lib/libMach1Decode-minifiedCAPI.a")
    endif()
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/lib" TYPE STATIC_LIBRARY FILES "/Volumes/git/m1-sdk/lib/_builds/ios/static/RelWithDebInfo/libMach1Decode-minifiedCAPI.a")
    if(EXISTS "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/lib/libMach1Decode-minifiedCAPI.a" AND
       NOT IS_SYMLINK "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/lib/libMach1Decode-minifiedCAPI.a")
      include(CMakeIOSInstallCombined)
      ios_install_combined("Mach1DecodeMINCAPIstatic" "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/lib/libMach1Decode-minifiedCAPI.a")
      execute_process(COMMAND "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib" "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/lib/libMach1Decode-minifiedCAPI.a")
    endif()
  endif()
endif()

if("x${CMAKE_INSTALL_COMPONENT}x" STREQUAL "xUnspecifiedx" OR NOT CMAKE_INSTALL_COMPONENT)
  if("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/libUnity" TYPE SHARED_LIBRARY FILES "/Volumes/git/m1-sdk/lib/_builds/ios/Debug${EFFECTIVE_PLATFORM_NAME}/libMach1DecodeCAPId.1.3.0.0.dylib")
    if(EXISTS "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/libUnity/libMach1DecodeCAPId.1.3.0.0.dylib" AND
       NOT IS_SYMLINK "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/libUnity/libMach1DecodeCAPId.1.3.0.0.dylib")
      include(CMakeIOSInstallCombined)
      ios_install_combined("Mach1DecodeCAPIshared" "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/libUnity/libMach1DecodeCAPId.1.3.0.0.dylib")
    endif()
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/libUnity" TYPE SHARED_LIBRARY FILES "/Volumes/git/m1-sdk/lib/_builds/ios/Release${EFFECTIVE_PLATFORM_NAME}/libMach1DecodeCAPI.1.3.0.0.dylib")
    if(EXISTS "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/libUnity/libMach1DecodeCAPI.1.3.0.0.dylib" AND
       NOT IS_SYMLINK "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/libUnity/libMach1DecodeCAPI.1.3.0.0.dylib")
      include(CMakeIOSInstallCombined)
      ios_install_combined("Mach1DecodeCAPIshared" "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/libUnity/libMach1DecodeCAPI.1.3.0.0.dylib")
    endif()
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/libUnity" TYPE SHARED_LIBRARY FILES "/Volumes/git/m1-sdk/lib/_builds/ios/MinSizeRel${EFFECTIVE_PLATFORM_NAME}/libMach1DecodeCAPI.1.3.0.0.dylib")
    if(EXISTS "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/libUnity/libMach1DecodeCAPI.1.3.0.0.dylib" AND
       NOT IS_SYMLINK "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/libUnity/libMach1DecodeCAPI.1.3.0.0.dylib")
      include(CMakeIOSInstallCombined)
      ios_install_combined("Mach1DecodeCAPIshared" "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/libUnity/libMach1DecodeCAPI.1.3.0.0.dylib")
    endif()
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/libUnity" TYPE SHARED_LIBRARY FILES "/Volumes/git/m1-sdk/lib/_builds/ios/RelWithDebInfo${EFFECTIVE_PLATFORM_NAME}/libMach1DecodeCAPI.1.3.0.0.dylib")
    if(EXISTS "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/libUnity/libMach1DecodeCAPI.1.3.0.0.dylib" AND
       NOT IS_SYMLINK "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/libUnity/libMach1DecodeCAPI.1.3.0.0.dylib")
      include(CMakeIOSInstallCombined)
      ios_install_combined("Mach1DecodeCAPIshared" "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/libUnity/libMach1DecodeCAPI.1.3.0.0.dylib")
    endif()
  endif()
endif()

if("x${CMAKE_INSTALL_COMPONENT}x" STREQUAL "xUnspecifiedx" OR NOT CMAKE_INSTALL_COMPONENT)
  if("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/libUnity" TYPE SHARED_LIBRARY FILES "/Volumes/git/m1-sdk/lib/_builds/ios/Debug${EFFECTIVE_PLATFORM_NAME}/libMach1DecodeCAPId.dylib")
    if(EXISTS "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/libUnity/libMach1DecodeCAPId.dylib" AND
       NOT IS_SYMLINK "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/libUnity/libMach1DecodeCAPId.dylib")
      include(CMakeIOSInstallCombined)
      ios_install_combined("Mach1DecodeCAPIshared" "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/libUnity/libMach1DecodeCAPId.dylib")
    endif()
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/libUnity" TYPE SHARED_LIBRARY FILES "/Volumes/git/m1-sdk/lib/_builds/ios/Release${EFFECTIVE_PLATFORM_NAME}/libMach1DecodeCAPI.dylib")
    if(EXISTS "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/libUnity/libMach1DecodeCAPI.dylib" AND
       NOT IS_SYMLINK "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/libUnity/libMach1DecodeCAPI.dylib")
      include(CMakeIOSInstallCombined)
      ios_install_combined("Mach1DecodeCAPIshared" "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/libUnity/libMach1DecodeCAPI.dylib")
    endif()
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/libUnity" TYPE SHARED_LIBRARY FILES "/Volumes/git/m1-sdk/lib/_builds/ios/MinSizeRel${EFFECTIVE_PLATFORM_NAME}/libMach1DecodeCAPI.dylib")
    if(EXISTS "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/libUnity/libMach1DecodeCAPI.dylib" AND
       NOT IS_SYMLINK "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/libUnity/libMach1DecodeCAPI.dylib")
      include(CMakeIOSInstallCombined)
      ios_install_combined("Mach1DecodeCAPIshared" "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/libUnity/libMach1DecodeCAPI.dylib")
    endif()
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/libUnity" TYPE SHARED_LIBRARY FILES "/Volumes/git/m1-sdk/lib/_builds/ios/RelWithDebInfo${EFFECTIVE_PLATFORM_NAME}/libMach1DecodeCAPI.dylib")
    if(EXISTS "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/libUnity/libMach1DecodeCAPI.dylib" AND
       NOT IS_SYMLINK "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/libUnity/libMach1DecodeCAPI.dylib")
      include(CMakeIOSInstallCombined)
      ios_install_combined("Mach1DecodeCAPIshared" "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/libUnity/libMach1DecodeCAPI.dylib")
    endif()
  endif()
endif()

if("x${CMAKE_INSTALL_COMPONENT}x" STREQUAL "xUnspecifiedx" OR NOT CMAKE_INSTALL_COMPONENT)
  if("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/libUnity" TYPE SHARED_LIBRARY FILES "/Volumes/git/m1-sdk/lib/_builds/ios/Debug${EFFECTIVE_PLATFORM_NAME}/libMach1DecodePositionalCAPId.1.3.0.0.dylib")
    if(EXISTS "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/libUnity/libMach1DecodePositionalCAPId.1.3.0.0.dylib" AND
       NOT IS_SYMLINK "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/libUnity/libMach1DecodePositionalCAPId.1.3.0.0.dylib")
      include(CMakeIOSInstallCombined)
      ios_install_combined("Mach1DecodePositionalCAPIshared" "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/libUnity/libMach1DecodePositionalCAPId.1.3.0.0.dylib")
    endif()
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/libUnity" TYPE SHARED_LIBRARY FILES "/Volumes/git/m1-sdk/lib/_builds/ios/Release${EFFECTIVE_PLATFORM_NAME}/libMach1DecodePositionalCAPI.1.3.0.0.dylib")
    if(EXISTS "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/libUnity/libMach1DecodePositionalCAPI.1.3.0.0.dylib" AND
       NOT IS_SYMLINK "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/libUnity/libMach1DecodePositionalCAPI.1.3.0.0.dylib")
      include(CMakeIOSInstallCombined)
      ios_install_combined("Mach1DecodePositionalCAPIshared" "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/libUnity/libMach1DecodePositionalCAPI.1.3.0.0.dylib")
    endif()
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/libUnity" TYPE SHARED_LIBRARY FILES "/Volumes/git/m1-sdk/lib/_builds/ios/MinSizeRel${EFFECTIVE_PLATFORM_NAME}/libMach1DecodePositionalCAPI.1.3.0.0.dylib")
    if(EXISTS "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/libUnity/libMach1DecodePositionalCAPI.1.3.0.0.dylib" AND
       NOT IS_SYMLINK "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/libUnity/libMach1DecodePositionalCAPI.1.3.0.0.dylib")
      include(CMakeIOSInstallCombined)
      ios_install_combined("Mach1DecodePositionalCAPIshared" "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/libUnity/libMach1DecodePositionalCAPI.1.3.0.0.dylib")
    endif()
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/libUnity" TYPE SHARED_LIBRARY FILES "/Volumes/git/m1-sdk/lib/_builds/ios/RelWithDebInfo${EFFECTIVE_PLATFORM_NAME}/libMach1DecodePositionalCAPI.1.3.0.0.dylib")
    if(EXISTS "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/libUnity/libMach1DecodePositionalCAPI.1.3.0.0.dylib" AND
       NOT IS_SYMLINK "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/libUnity/libMach1DecodePositionalCAPI.1.3.0.0.dylib")
      include(CMakeIOSInstallCombined)
      ios_install_combined("Mach1DecodePositionalCAPIshared" "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/libUnity/libMach1DecodePositionalCAPI.1.3.0.0.dylib")
    endif()
  endif()
endif()

if("x${CMAKE_INSTALL_COMPONENT}x" STREQUAL "xUnspecifiedx" OR NOT CMAKE_INSTALL_COMPONENT)
  if("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/libUnity" TYPE SHARED_LIBRARY FILES "/Volumes/git/m1-sdk/lib/_builds/ios/Debug${EFFECTIVE_PLATFORM_NAME}/libMach1DecodePositionalCAPId.dylib")
    if(EXISTS "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/libUnity/libMach1DecodePositionalCAPId.dylib" AND
       NOT IS_SYMLINK "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/libUnity/libMach1DecodePositionalCAPId.dylib")
      include(CMakeIOSInstallCombined)
      ios_install_combined("Mach1DecodePositionalCAPIshared" "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/libUnity/libMach1DecodePositionalCAPId.dylib")
    endif()
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/libUnity" TYPE SHARED_LIBRARY FILES "/Volumes/git/m1-sdk/lib/_builds/ios/Release${EFFECTIVE_PLATFORM_NAME}/libMach1DecodePositionalCAPI.dylib")
    if(EXISTS "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/libUnity/libMach1DecodePositionalCAPI.dylib" AND
       NOT IS_SYMLINK "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/libUnity/libMach1DecodePositionalCAPI.dylib")
      include(CMakeIOSInstallCombined)
      ios_install_combined("Mach1DecodePositionalCAPIshared" "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/libUnity/libMach1DecodePositionalCAPI.dylib")
    endif()
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/libUnity" TYPE SHARED_LIBRARY FILES "/Volumes/git/m1-sdk/lib/_builds/ios/MinSizeRel${EFFECTIVE_PLATFORM_NAME}/libMach1DecodePositionalCAPI.dylib")
    if(EXISTS "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/libUnity/libMach1DecodePositionalCAPI.dylib" AND
       NOT IS_SYMLINK "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/libUnity/libMach1DecodePositionalCAPI.dylib")
      include(CMakeIOSInstallCombined)
      ios_install_combined("Mach1DecodePositionalCAPIshared" "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/libUnity/libMach1DecodePositionalCAPI.dylib")
    endif()
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/libUnity" TYPE SHARED_LIBRARY FILES "/Volumes/git/m1-sdk/lib/_builds/ios/RelWithDebInfo${EFFECTIVE_PLATFORM_NAME}/libMach1DecodePositionalCAPI.dylib")
    if(EXISTS "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/libUnity/libMach1DecodePositionalCAPI.dylib" AND
       NOT IS_SYMLINK "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/libUnity/libMach1DecodePositionalCAPI.dylib")
      include(CMakeIOSInstallCombined)
      ios_install_combined("Mach1DecodePositionalCAPIshared" "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/libUnity/libMach1DecodePositionalCAPI.dylib")
    endif()
  endif()
endif()

if("x${CMAKE_INSTALL_COMPONENT}x" STREQUAL "xUnspecifiedx" OR NOT CMAKE_INSTALL_COMPONENT)
  if("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/libUnity" TYPE SHARED_LIBRARY FILES "/Volumes/git/m1-sdk/lib/_builds/ios/Debug${EFFECTIVE_PLATFORM_NAME}/libMach1EncodeCAPId.1.4.0.0.dylib")
    if(EXISTS "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/libUnity/libMach1EncodeCAPId.1.4.0.0.dylib" AND
       NOT IS_SYMLINK "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/libUnity/libMach1EncodeCAPId.1.4.0.0.dylib")
      include(CMakeIOSInstallCombined)
      ios_install_combined("Mach1EncodeCAPIshared" "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/libUnity/libMach1EncodeCAPId.1.4.0.0.dylib")
    endif()
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/libUnity" TYPE SHARED_LIBRARY FILES "/Volumes/git/m1-sdk/lib/_builds/ios/Release${EFFECTIVE_PLATFORM_NAME}/libMach1EncodeCAPI.1.4.0.0.dylib")
    if(EXISTS "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/libUnity/libMach1EncodeCAPI.1.4.0.0.dylib" AND
       NOT IS_SYMLINK "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/libUnity/libMach1EncodeCAPI.1.4.0.0.dylib")
      include(CMakeIOSInstallCombined)
      ios_install_combined("Mach1EncodeCAPIshared" "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/libUnity/libMach1EncodeCAPI.1.4.0.0.dylib")
    endif()
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/libUnity" TYPE SHARED_LIBRARY FILES "/Volumes/git/m1-sdk/lib/_builds/ios/MinSizeRel${EFFECTIVE_PLATFORM_NAME}/libMach1EncodeCAPI.1.4.0.0.dylib")
    if(EXISTS "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/libUnity/libMach1EncodeCAPI.1.4.0.0.dylib" AND
       NOT IS_SYMLINK "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/libUnity/libMach1EncodeCAPI.1.4.0.0.dylib")
      include(CMakeIOSInstallCombined)
      ios_install_combined("Mach1EncodeCAPIshared" "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/libUnity/libMach1EncodeCAPI.1.4.0.0.dylib")
    endif()
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/libUnity" TYPE SHARED_LIBRARY FILES "/Volumes/git/m1-sdk/lib/_builds/ios/RelWithDebInfo${EFFECTIVE_PLATFORM_NAME}/libMach1EncodeCAPI.1.4.0.0.dylib")
    if(EXISTS "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/libUnity/libMach1EncodeCAPI.1.4.0.0.dylib" AND
       NOT IS_SYMLINK "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/libUnity/libMach1EncodeCAPI.1.4.0.0.dylib")
      include(CMakeIOSInstallCombined)
      ios_install_combined("Mach1EncodeCAPIshared" "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/libUnity/libMach1EncodeCAPI.1.4.0.0.dylib")
    endif()
  endif()
endif()

if("x${CMAKE_INSTALL_COMPONENT}x" STREQUAL "xUnspecifiedx" OR NOT CMAKE_INSTALL_COMPONENT)
  if("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/libUnity" TYPE SHARED_LIBRARY FILES "/Volumes/git/m1-sdk/lib/_builds/ios/Debug${EFFECTIVE_PLATFORM_NAME}/libMach1EncodeCAPId.dylib")
    if(EXISTS "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/libUnity/libMach1EncodeCAPId.dylib" AND
       NOT IS_SYMLINK "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/libUnity/libMach1EncodeCAPId.dylib")
      include(CMakeIOSInstallCombined)
      ios_install_combined("Mach1EncodeCAPIshared" "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/libUnity/libMach1EncodeCAPId.dylib")
    endif()
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/libUnity" TYPE SHARED_LIBRARY FILES "/Volumes/git/m1-sdk/lib/_builds/ios/Release${EFFECTIVE_PLATFORM_NAME}/libMach1EncodeCAPI.dylib")
    if(EXISTS "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/libUnity/libMach1EncodeCAPI.dylib" AND
       NOT IS_SYMLINK "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/libUnity/libMach1EncodeCAPI.dylib")
      include(CMakeIOSInstallCombined)
      ios_install_combined("Mach1EncodeCAPIshared" "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/libUnity/libMach1EncodeCAPI.dylib")
    endif()
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/libUnity" TYPE SHARED_LIBRARY FILES "/Volumes/git/m1-sdk/lib/_builds/ios/MinSizeRel${EFFECTIVE_PLATFORM_NAME}/libMach1EncodeCAPI.dylib")
    if(EXISTS "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/libUnity/libMach1EncodeCAPI.dylib" AND
       NOT IS_SYMLINK "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/libUnity/libMach1EncodeCAPI.dylib")
      include(CMakeIOSInstallCombined)
      ios_install_combined("Mach1EncodeCAPIshared" "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/libUnity/libMach1EncodeCAPI.dylib")
    endif()
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/libUnity" TYPE SHARED_LIBRARY FILES "/Volumes/git/m1-sdk/lib/_builds/ios/RelWithDebInfo${EFFECTIVE_PLATFORM_NAME}/libMach1EncodeCAPI.dylib")
    if(EXISTS "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/libUnity/libMach1EncodeCAPI.dylib" AND
       NOT IS_SYMLINK "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/libUnity/libMach1EncodeCAPI.dylib")
      include(CMakeIOSInstallCombined)
      ios_install_combined("Mach1EncodeCAPIshared" "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/libUnity/libMach1EncodeCAPI.dylib")
    endif()
  endif()
endif()

if("x${CMAKE_INSTALL_COMPONENT}x" STREQUAL "xUnspecifiedx" OR NOT CMAKE_INSTALL_COMPONENT)
  if("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/libUnity" TYPE SHARED_LIBRARY FILES "/Volumes/git/m1-sdk/lib/_builds/ios/Debug${EFFECTIVE_PLATFORM_NAME}/libMach1TranscodeCAPId.1.4.1.2.dylib")
    if(EXISTS "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/libUnity/libMach1TranscodeCAPId.1.4.1.2.dylib" AND
       NOT IS_SYMLINK "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/libUnity/libMach1TranscodeCAPId.1.4.1.2.dylib")
      include(CMakeIOSInstallCombined)
      ios_install_combined("Mach1TranscodeCAPIshared" "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/libUnity/libMach1TranscodeCAPId.1.4.1.2.dylib")
    endif()
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/libUnity" TYPE SHARED_LIBRARY FILES "/Volumes/git/m1-sdk/lib/_builds/ios/Release${EFFECTIVE_PLATFORM_NAME}/libMach1TranscodeCAPI.1.4.1.2.dylib")
    if(EXISTS "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/libUnity/libMach1TranscodeCAPI.1.4.1.2.dylib" AND
       NOT IS_SYMLINK "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/libUnity/libMach1TranscodeCAPI.1.4.1.2.dylib")
      include(CMakeIOSInstallCombined)
      ios_install_combined("Mach1TranscodeCAPIshared" "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/libUnity/libMach1TranscodeCAPI.1.4.1.2.dylib")
    endif()
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/libUnity" TYPE SHARED_LIBRARY FILES "/Volumes/git/m1-sdk/lib/_builds/ios/MinSizeRel${EFFECTIVE_PLATFORM_NAME}/libMach1TranscodeCAPI.1.4.1.2.dylib")
    if(EXISTS "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/libUnity/libMach1TranscodeCAPI.1.4.1.2.dylib" AND
       NOT IS_SYMLINK "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/libUnity/libMach1TranscodeCAPI.1.4.1.2.dylib")
      include(CMakeIOSInstallCombined)
      ios_install_combined("Mach1TranscodeCAPIshared" "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/libUnity/libMach1TranscodeCAPI.1.4.1.2.dylib")
    endif()
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/libUnity" TYPE SHARED_LIBRARY FILES "/Volumes/git/m1-sdk/lib/_builds/ios/RelWithDebInfo${EFFECTIVE_PLATFORM_NAME}/libMach1TranscodeCAPI.1.4.1.2.dylib")
    if(EXISTS "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/libUnity/libMach1TranscodeCAPI.1.4.1.2.dylib" AND
       NOT IS_SYMLINK "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/libUnity/libMach1TranscodeCAPI.1.4.1.2.dylib")
      include(CMakeIOSInstallCombined)
      ios_install_combined("Mach1TranscodeCAPIshared" "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/libUnity/libMach1TranscodeCAPI.1.4.1.2.dylib")
    endif()
  endif()
endif()

if("x${CMAKE_INSTALL_COMPONENT}x" STREQUAL "xUnspecifiedx" OR NOT CMAKE_INSTALL_COMPONENT)
  if("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/libUnity" TYPE SHARED_LIBRARY FILES "/Volumes/git/m1-sdk/lib/_builds/ios/Debug${EFFECTIVE_PLATFORM_NAME}/libMach1TranscodeCAPId.dylib")
    if(EXISTS "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/libUnity/libMach1TranscodeCAPId.dylib" AND
       NOT IS_SYMLINK "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/libUnity/libMach1TranscodeCAPId.dylib")
      include(CMakeIOSInstallCombined)
      ios_install_combined("Mach1TranscodeCAPIshared" "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/libUnity/libMach1TranscodeCAPId.dylib")
    endif()
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/libUnity" TYPE SHARED_LIBRARY FILES "/Volumes/git/m1-sdk/lib/_builds/ios/Release${EFFECTIVE_PLATFORM_NAME}/libMach1TranscodeCAPI.dylib")
    if(EXISTS "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/libUnity/libMach1TranscodeCAPI.dylib" AND
       NOT IS_SYMLINK "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/libUnity/libMach1TranscodeCAPI.dylib")
      include(CMakeIOSInstallCombined)
      ios_install_combined("Mach1TranscodeCAPIshared" "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/libUnity/libMach1TranscodeCAPI.dylib")
    endif()
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/libUnity" TYPE SHARED_LIBRARY FILES "/Volumes/git/m1-sdk/lib/_builds/ios/MinSizeRel${EFFECTIVE_PLATFORM_NAME}/libMach1TranscodeCAPI.dylib")
    if(EXISTS "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/libUnity/libMach1TranscodeCAPI.dylib" AND
       NOT IS_SYMLINK "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/libUnity/libMach1TranscodeCAPI.dylib")
      include(CMakeIOSInstallCombined)
      ios_install_combined("Mach1TranscodeCAPIshared" "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/libUnity/libMach1TranscodeCAPI.dylib")
    endif()
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/libUnity" TYPE SHARED_LIBRARY FILES "/Volumes/git/m1-sdk/lib/_builds/ios/RelWithDebInfo${EFFECTIVE_PLATFORM_NAME}/libMach1TranscodeCAPI.dylib")
    if(EXISTS "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/libUnity/libMach1TranscodeCAPI.dylib" AND
       NOT IS_SYMLINK "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/libUnity/libMach1TranscodeCAPI.dylib")
      include(CMakeIOSInstallCombined)
      ios_install_combined("Mach1TranscodeCAPIshared" "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/libUnity/libMach1TranscodeCAPI.dylib")
    endif()
  endif()
endif()

if("x${CMAKE_INSTALL_COMPONENT}x" STREQUAL "xUnspecifiedx" OR NOT CMAKE_INSTALL_COMPONENT)
  if("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/Frameworks" TYPE DIRECTORY FILES "/Volumes/git/m1-sdk/lib/_builds/ios/static/Debug/Mach1DecodeCAPI.framework" USE_SOURCE_PERMISSIONS)
    if(EXISTS "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/Frameworks/Mach1DecodeCAPI.framework/Mach1DecodeCAPI" AND
       NOT IS_SYMLINK "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/Frameworks/Mach1DecodeCAPI.framework/Mach1DecodeCAPI")
      include(CMakeIOSInstallCombined)
      ios_install_combined("Mach1DecodeCAPIframework" "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/Frameworks/Mach1DecodeCAPI.framework/Mach1DecodeCAPI")
      execute_process(COMMAND "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib" "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/Frameworks/Mach1DecodeCAPI.framework/Mach1DecodeCAPI")
    endif()
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/Frameworks" TYPE DIRECTORY FILES "/Volumes/git/m1-sdk/lib/_builds/ios/static/Release/Mach1DecodeCAPI.framework" USE_SOURCE_PERMISSIONS)
    if(EXISTS "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/Frameworks/Mach1DecodeCAPI.framework/Mach1DecodeCAPI" AND
       NOT IS_SYMLINK "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/Frameworks/Mach1DecodeCAPI.framework/Mach1DecodeCAPI")
      include(CMakeIOSInstallCombined)
      ios_install_combined("Mach1DecodeCAPIframework" "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/Frameworks/Mach1DecodeCAPI.framework/Mach1DecodeCAPI")
      execute_process(COMMAND "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib" "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/Frameworks/Mach1DecodeCAPI.framework/Mach1DecodeCAPI")
    endif()
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/Frameworks" TYPE DIRECTORY FILES "/Volumes/git/m1-sdk/lib/_builds/ios/static/MinSizeRel/Mach1DecodeCAPI.framework" USE_SOURCE_PERMISSIONS)
    if(EXISTS "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/Frameworks/Mach1DecodeCAPI.framework/Mach1DecodeCAPI" AND
       NOT IS_SYMLINK "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/Frameworks/Mach1DecodeCAPI.framework/Mach1DecodeCAPI")
      include(CMakeIOSInstallCombined)
      ios_install_combined("Mach1DecodeCAPIframework" "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/Frameworks/Mach1DecodeCAPI.framework/Mach1DecodeCAPI")
      execute_process(COMMAND "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib" "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/Frameworks/Mach1DecodeCAPI.framework/Mach1DecodeCAPI")
    endif()
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/Frameworks" TYPE DIRECTORY FILES "/Volumes/git/m1-sdk/lib/_builds/ios/static/RelWithDebInfo/Mach1DecodeCAPI.framework" USE_SOURCE_PERMISSIONS)
    if(EXISTS "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/Frameworks/Mach1DecodeCAPI.framework/Mach1DecodeCAPI" AND
       NOT IS_SYMLINK "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/Frameworks/Mach1DecodeCAPI.framework/Mach1DecodeCAPI")
      include(CMakeIOSInstallCombined)
      ios_install_combined("Mach1DecodeCAPIframework" "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/Frameworks/Mach1DecodeCAPI.framework/Mach1DecodeCAPI")
      execute_process(COMMAND "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib" "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/Frameworks/Mach1DecodeCAPI.framework/Mach1DecodeCAPI")
    endif()
  endif()
endif()

if("x${CMAKE_INSTALL_COMPONENT}x" STREQUAL "xUnspecifiedx" OR NOT CMAKE_INSTALL_COMPONENT)
  if("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/Frameworks" TYPE DIRECTORY FILES "/Volumes/git/m1-sdk/lib/_builds/ios/static/Debug/Mach1DecodePositionalCAPI.framework" USE_SOURCE_PERMISSIONS)
    if(EXISTS "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/Frameworks/Mach1DecodePositionalCAPI.framework/Mach1DecodePositionalCAPI" AND
       NOT IS_SYMLINK "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/Frameworks/Mach1DecodePositionalCAPI.framework/Mach1DecodePositionalCAPI")
      include(CMakeIOSInstallCombined)
      ios_install_combined("Mach1DecodePositionalCAPIframework" "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/Frameworks/Mach1DecodePositionalCAPI.framework/Mach1DecodePositionalCAPI")
      execute_process(COMMAND "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib" "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/Frameworks/Mach1DecodePositionalCAPI.framework/Mach1DecodePositionalCAPI")
    endif()
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/Frameworks" TYPE DIRECTORY FILES "/Volumes/git/m1-sdk/lib/_builds/ios/static/Release/Mach1DecodePositionalCAPI.framework" USE_SOURCE_PERMISSIONS)
    if(EXISTS "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/Frameworks/Mach1DecodePositionalCAPI.framework/Mach1DecodePositionalCAPI" AND
       NOT IS_SYMLINK "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/Frameworks/Mach1DecodePositionalCAPI.framework/Mach1DecodePositionalCAPI")
      include(CMakeIOSInstallCombined)
      ios_install_combined("Mach1DecodePositionalCAPIframework" "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/Frameworks/Mach1DecodePositionalCAPI.framework/Mach1DecodePositionalCAPI")
      execute_process(COMMAND "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib" "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/Frameworks/Mach1DecodePositionalCAPI.framework/Mach1DecodePositionalCAPI")
    endif()
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/Frameworks" TYPE DIRECTORY FILES "/Volumes/git/m1-sdk/lib/_builds/ios/static/MinSizeRel/Mach1DecodePositionalCAPI.framework" USE_SOURCE_PERMISSIONS)
    if(EXISTS "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/Frameworks/Mach1DecodePositionalCAPI.framework/Mach1DecodePositionalCAPI" AND
       NOT IS_SYMLINK "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/Frameworks/Mach1DecodePositionalCAPI.framework/Mach1DecodePositionalCAPI")
      include(CMakeIOSInstallCombined)
      ios_install_combined("Mach1DecodePositionalCAPIframework" "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/Frameworks/Mach1DecodePositionalCAPI.framework/Mach1DecodePositionalCAPI")
      execute_process(COMMAND "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib" "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/Frameworks/Mach1DecodePositionalCAPI.framework/Mach1DecodePositionalCAPI")
    endif()
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/Frameworks" TYPE DIRECTORY FILES "/Volumes/git/m1-sdk/lib/_builds/ios/static/RelWithDebInfo/Mach1DecodePositionalCAPI.framework" USE_SOURCE_PERMISSIONS)
    if(EXISTS "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/Frameworks/Mach1DecodePositionalCAPI.framework/Mach1DecodePositionalCAPI" AND
       NOT IS_SYMLINK "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/Frameworks/Mach1DecodePositionalCAPI.framework/Mach1DecodePositionalCAPI")
      include(CMakeIOSInstallCombined)
      ios_install_combined("Mach1DecodePositionalCAPIframework" "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/Frameworks/Mach1DecodePositionalCAPI.framework/Mach1DecodePositionalCAPI")
      execute_process(COMMAND "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib" "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/Frameworks/Mach1DecodePositionalCAPI.framework/Mach1DecodePositionalCAPI")
    endif()
  endif()
endif()

if("x${CMAKE_INSTALL_COMPONENT}x" STREQUAL "xUnspecifiedx" OR NOT CMAKE_INSTALL_COMPONENT)
  if("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/Frameworks" TYPE DIRECTORY FILES "/Volumes/git/m1-sdk/lib/_builds/ios/static/Debug/Mach1EncodeCAPI.framework" USE_SOURCE_PERMISSIONS)
    if(EXISTS "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/Frameworks/Mach1EncodeCAPI.framework/Mach1EncodeCAPI" AND
       NOT IS_SYMLINK "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/Frameworks/Mach1EncodeCAPI.framework/Mach1EncodeCAPI")
      include(CMakeIOSInstallCombined)
      ios_install_combined("Mach1EncodeCAPIframework" "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/Frameworks/Mach1EncodeCAPI.framework/Mach1EncodeCAPI")
      execute_process(COMMAND "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib" "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/Frameworks/Mach1EncodeCAPI.framework/Mach1EncodeCAPI")
    endif()
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/Frameworks" TYPE DIRECTORY FILES "/Volumes/git/m1-sdk/lib/_builds/ios/static/Release/Mach1EncodeCAPI.framework" USE_SOURCE_PERMISSIONS)
    if(EXISTS "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/Frameworks/Mach1EncodeCAPI.framework/Mach1EncodeCAPI" AND
       NOT IS_SYMLINK "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/Frameworks/Mach1EncodeCAPI.framework/Mach1EncodeCAPI")
      include(CMakeIOSInstallCombined)
      ios_install_combined("Mach1EncodeCAPIframework" "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/Frameworks/Mach1EncodeCAPI.framework/Mach1EncodeCAPI")
      execute_process(COMMAND "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib" "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/Frameworks/Mach1EncodeCAPI.framework/Mach1EncodeCAPI")
    endif()
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/Frameworks" TYPE DIRECTORY FILES "/Volumes/git/m1-sdk/lib/_builds/ios/static/MinSizeRel/Mach1EncodeCAPI.framework" USE_SOURCE_PERMISSIONS)
    if(EXISTS "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/Frameworks/Mach1EncodeCAPI.framework/Mach1EncodeCAPI" AND
       NOT IS_SYMLINK "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/Frameworks/Mach1EncodeCAPI.framework/Mach1EncodeCAPI")
      include(CMakeIOSInstallCombined)
      ios_install_combined("Mach1EncodeCAPIframework" "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/Frameworks/Mach1EncodeCAPI.framework/Mach1EncodeCAPI")
      execute_process(COMMAND "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib" "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/Frameworks/Mach1EncodeCAPI.framework/Mach1EncodeCAPI")
    endif()
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/Frameworks" TYPE DIRECTORY FILES "/Volumes/git/m1-sdk/lib/_builds/ios/static/RelWithDebInfo/Mach1EncodeCAPI.framework" USE_SOURCE_PERMISSIONS)
    if(EXISTS "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/Frameworks/Mach1EncodeCAPI.framework/Mach1EncodeCAPI" AND
       NOT IS_SYMLINK "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/Frameworks/Mach1EncodeCAPI.framework/Mach1EncodeCAPI")
      include(CMakeIOSInstallCombined)
      ios_install_combined("Mach1EncodeCAPIframework" "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/Frameworks/Mach1EncodeCAPI.framework/Mach1EncodeCAPI")
      execute_process(COMMAND "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib" "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/Frameworks/Mach1EncodeCAPI.framework/Mach1EncodeCAPI")
    endif()
  endif()
endif()

if("x${CMAKE_INSTALL_COMPONENT}x" STREQUAL "xUnspecifiedx" OR NOT CMAKE_INSTALL_COMPONENT)
  if("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/Frameworks" TYPE DIRECTORY FILES "/Volumes/git/m1-sdk/lib/_builds/ios/static/Debug/Mach1TranscodeCAPI.framework" USE_SOURCE_PERMISSIONS)
    if(EXISTS "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/Frameworks/Mach1TranscodeCAPI.framework/Mach1TranscodeCAPI" AND
       NOT IS_SYMLINK "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/Frameworks/Mach1TranscodeCAPI.framework/Mach1TranscodeCAPI")
      include(CMakeIOSInstallCombined)
      ios_install_combined("Mach1TranscodeCAPIframework" "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/Frameworks/Mach1TranscodeCAPI.framework/Mach1TranscodeCAPI")
      execute_process(COMMAND "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib" "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/Frameworks/Mach1TranscodeCAPI.framework/Mach1TranscodeCAPI")
    endif()
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/Frameworks" TYPE DIRECTORY FILES "/Volumes/git/m1-sdk/lib/_builds/ios/static/Release/Mach1TranscodeCAPI.framework" USE_SOURCE_PERMISSIONS)
    if(EXISTS "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/Frameworks/Mach1TranscodeCAPI.framework/Mach1TranscodeCAPI" AND
       NOT IS_SYMLINK "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/Frameworks/Mach1TranscodeCAPI.framework/Mach1TranscodeCAPI")
      include(CMakeIOSInstallCombined)
      ios_install_combined("Mach1TranscodeCAPIframework" "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/Frameworks/Mach1TranscodeCAPI.framework/Mach1TranscodeCAPI")
      execute_process(COMMAND "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib" "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/Frameworks/Mach1TranscodeCAPI.framework/Mach1TranscodeCAPI")
    endif()
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/Frameworks" TYPE DIRECTORY FILES "/Volumes/git/m1-sdk/lib/_builds/ios/static/MinSizeRel/Mach1TranscodeCAPI.framework" USE_SOURCE_PERMISSIONS)
    if(EXISTS "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/Frameworks/Mach1TranscodeCAPI.framework/Mach1TranscodeCAPI" AND
       NOT IS_SYMLINK "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/Frameworks/Mach1TranscodeCAPI.framework/Mach1TranscodeCAPI")
      include(CMakeIOSInstallCombined)
      ios_install_combined("Mach1TranscodeCAPIframework" "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/Frameworks/Mach1TranscodeCAPI.framework/Mach1TranscodeCAPI")
      execute_process(COMMAND "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib" "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/Frameworks/Mach1TranscodeCAPI.framework/Mach1TranscodeCAPI")
    endif()
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/Frameworks" TYPE DIRECTORY FILES "/Volumes/git/m1-sdk/lib/_builds/ios/static/RelWithDebInfo/Mach1TranscodeCAPI.framework" USE_SOURCE_PERMISSIONS)
    if(EXISTS "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/Frameworks/Mach1TranscodeCAPI.framework/Mach1TranscodeCAPI" AND
       NOT IS_SYMLINK "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/Frameworks/Mach1TranscodeCAPI.framework/Mach1TranscodeCAPI")
      include(CMakeIOSInstallCombined)
      ios_install_combined("Mach1TranscodeCAPIframework" "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/Frameworks/Mach1TranscodeCAPI.framework/Mach1TranscodeCAPI")
      execute_process(COMMAND "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib" "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/Frameworks/Mach1TranscodeCAPI.framework/Mach1TranscodeCAPI")
    endif()
  endif()
endif()

if(CMAKE_INSTALL_COMPONENT)
  set(CMAKE_INSTALL_MANIFEST "install_manifest_${CMAKE_INSTALL_COMPONENT}.txt")
else()
  set(CMAKE_INSTALL_MANIFEST "install_manifest.txt")
endif()

string(REPLACE ";" "\n" CMAKE_INSTALL_MANIFEST_CONTENT
       "${CMAKE_INSTALL_MANIFEST_FILES}")
file(WRITE "/Volumes/git/m1-sdk/lib/_builds/ios/${CMAKE_INSTALL_MANIFEST}"
     "${CMAKE_INSTALL_MANIFEST_CONTENT}")
