/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.mach1.spatiallibs;

class Mach1FloatArrayModuleJNI {
 
  static {
    System.loadLibrary("Mach1FloatArrayModule_lib");
  }

  public final static native long new_Mach1FloatArray(int jarg1);
  public final static native void delete_Mach1FloatArray(long jarg1);
  public final static native float Mach1FloatArray_getitem(long jarg1, Mach1FloatArray jarg1_, int jarg2);
  public final static native void Mach1FloatArray_setitem(long jarg1, Mach1FloatArray jarg1_, int jarg2, float jarg3);
  public final static native long Mach1FloatArray_cast(long jarg1, Mach1FloatArray jarg1_);
  public final static native long Mach1FloatArray_frompointer(long jarg1);
}
