/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * This file is not intended to be easily readable and contains a number of
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG
 * interface file instead.
 * ----------------------------------------------------------------------------- */


#ifndef SWIGJAVA
#define SWIGJAVA
#endif



#ifdef __cplusplus
/* SwigValueWrapper is described in swig.swg */
template<typename T> class SwigValueWrapper {
  struct SwigMovePointer {
    T *ptr;
    SwigMovePointer(T *p) : ptr(p) { }
    ~SwigMovePointer() { delete ptr; }
    SwigMovePointer& operator=(SwigMovePointer& rhs) { T* oldptr = ptr; ptr = 0; delete oldptr; ptr = rhs.ptr; rhs.ptr = 0; return *this; }
  } pointer;
  SwigValueWrapper& operator=(const SwigValueWrapper<T>& rhs);
  SwigValueWrapper(const SwigValueWrapper<T>& rhs);
public:
  SwigValueWrapper() : pointer(0) { }
  SwigValueWrapper& operator=(const T& t) { SwigMovePointer tmp(new T(t)); pointer = tmp; return *this; }
  operator T&() const { return *pointer.ptr; }
  T *operator&() { return pointer.ptr; }
};

template <typename T> T SwigValueInit() {
  return T();
}
#endif

/* -----------------------------------------------------------------------------
 *  This section contains generic SWIG labels for method/variable
 *  declarations/attributes, and other compiler dependent labels.
 * ----------------------------------------------------------------------------- */

/* template workaround for compilers that cannot correctly implement the C++ standard */
#ifndef SWIGTEMPLATEDISAMBIGUATOR
# if defined(__SUNPRO_CC) && (__SUNPRO_CC <= 0x560)
#  define SWIGTEMPLATEDISAMBIGUATOR template
# elif defined(__HP_aCC)
/* Needed even with `aCC -AA' when `aCC -V' reports HP ANSI C++ B3910B A.03.55 */
/* If we find a maximum version that requires this, the test would be __HP_aCC <= 35500 for A.03.55 */
#  define SWIGTEMPLATEDISAMBIGUATOR template
# else
#  define SWIGTEMPLATEDISAMBIGUATOR
# endif
#endif

/* inline attribute */
#ifndef SWIGINLINE
# if defined(__cplusplus) || (defined(__GNUC__) && !defined(__STRICT_ANSI__))
#   define SWIGINLINE inline
# else
#   define SWIGINLINE
# endif
#endif

/* attribute recognised by some compilers to avoid 'unused' warnings */
#ifndef SWIGUNUSED
# if defined(__GNUC__)
#   if !(defined(__cplusplus)) || (__GNUC__ > 3 || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4))
#     define SWIGUNUSED __attribute__ ((__unused__))
#   else
#     define SWIGUNUSED
#   endif
# elif defined(__ICC)
#   define SWIGUNUSED __attribute__ ((__unused__))
# else
#   define SWIGUNUSED
# endif
#endif

#ifndef SWIG_MSC_UNSUPPRESS_4505
# if defined(_MSC_VER)
#   pragma warning(disable : 4505) /* unreferenced local function has been removed */
# endif
#endif

#ifndef SWIGUNUSEDPARM
# ifdef __cplusplus
#   define SWIGUNUSEDPARM(p)
# else
#   define SWIGUNUSEDPARM(p) p SWIGUNUSED
# endif
#endif

/* internal SWIG method */
#ifndef SWIGINTERN
# define SWIGINTERN static SWIGUNUSED
#endif

/* internal inline SWIG method */
#ifndef SWIGINTERNINLINE
# define SWIGINTERNINLINE SWIGINTERN SWIGINLINE
#endif

/* exporting methods */
#if defined(__GNUC__)
#  if (__GNUC__ >= 4) || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4)
#    ifndef GCC_HASCLASSVISIBILITY
#      define GCC_HASCLASSVISIBILITY
#    endif
#  endif
#endif

#ifndef SWIGEXPORT
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   if defined(STATIC_LINKED)
#     define SWIGEXPORT
#   else
#     define SWIGEXPORT __declspec(dllexport)
#   endif
# else
#   if defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
#     define SWIGEXPORT __attribute__ ((visibility("default")))
#   else
#     define SWIGEXPORT
#   endif
# endif
#endif

/* calling conventions for Windows */
#ifndef SWIGSTDCALL
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   define SWIGSTDCALL __stdcall
# else
#   define SWIGSTDCALL
# endif
#endif

/* Deal with Microsoft's attempt at deprecating C standard runtime functions */
#if !defined(SWIG_NO_CRT_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_CRT_SECURE_NO_DEPRECATE)
# define _CRT_SECURE_NO_DEPRECATE
#endif

/* Deal with Microsoft's attempt at deprecating methods in the standard C++ library */
#if !defined(SWIG_NO_SCL_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_SCL_SECURE_NO_DEPRECATE)
# define _SCL_SECURE_NO_DEPRECATE
#endif

/* Deal with Apple's deprecated 'AssertMacros.h' from Carbon-framework */
#if defined(__APPLE__) && !defined(__ASSERT_MACROS_DEFINE_VERSIONS_WITHOUT_UNDERSCORES)
# define __ASSERT_MACROS_DEFINE_VERSIONS_WITHOUT_UNDERSCORES 0
#endif

/* Intel's compiler complains if a variable which was never initialised is
 * cast to void, which is a common idiom which we use to indicate that we
 * are aware a variable isn't used.  So we just silence that warning.
 * See: https://github.com/swig/swig/issues/192 for more discussion.
 */
#ifdef __INTEL_COMPILER
# pragma warning disable 592
#endif


/* Fix for jlong on some versions of gcc on Windows */
#if defined(__GNUC__) && !defined(__INTEL_COMPILER)
  typedef long long __int64;
#endif

/* Fix for jlong on 64-bit x86 Solaris */
#if defined(__x86_64)
# ifdef _LP64
#   undef _LP64
# endif
#endif

#include <jni.h>
#include <stdlib.h>
#include <string.h>


/* Support for throwing Java exceptions */
typedef enum {
  SWIG_JavaOutOfMemoryError = 1,
  SWIG_JavaIOException,
  SWIG_JavaRuntimeException,
  SWIG_JavaIndexOutOfBoundsException,
  SWIG_JavaArithmeticException,
  SWIG_JavaIllegalArgumentException,
  SWIG_JavaNullPointerException,
  SWIG_JavaDirectorPureVirtual,
  SWIG_JavaUnknownError,
  SWIG_JavaIllegalStateException,
} SWIG_JavaExceptionCodes;

typedef struct {
  SWIG_JavaExceptionCodes code;
  const char *java_exception;
} SWIG_JavaExceptions_t;


static void SWIGUNUSED SWIG_JavaThrowException(JNIEnv *jenv, SWIG_JavaExceptionCodes code, const char *msg) {
  jclass excep;
  static const SWIG_JavaExceptions_t java_exceptions[] = {
    { SWIG_JavaOutOfMemoryError, "java/lang/OutOfMemoryError" },
    { SWIG_JavaIOException, "java/io/IOException" },
    { SWIG_JavaRuntimeException, "java/lang/RuntimeException" },
    { SWIG_JavaIndexOutOfBoundsException, "java/lang/IndexOutOfBoundsException" },
    { SWIG_JavaArithmeticException, "java/lang/ArithmeticException" },
    { SWIG_JavaIllegalArgumentException, "java/lang/IllegalArgumentException" },
    { SWIG_JavaNullPointerException, "java/lang/NullPointerException" },
    { SWIG_JavaDirectorPureVirtual, "java/lang/RuntimeException" },
    { SWIG_JavaUnknownError,  "java/lang/UnknownError" },
    { SWIG_JavaIllegalStateException, "java/lang/IllegalStateException" },
    { (SWIG_JavaExceptionCodes)0,  "java/lang/UnknownError" }
  };
  const SWIG_JavaExceptions_t *except_ptr = java_exceptions;

  while (except_ptr->code != code && except_ptr->code)
    except_ptr++;

  jenv->ExceptionClear();
  excep = jenv->FindClass(except_ptr->java_exception);
  if (excep)
    jenv->ThrowNew(excep, msg);
}


/* Contract support */

#define SWIG_contract_assert(nullreturn, expr, msg) if (!(expr)) {SWIG_JavaThrowException(jenv, SWIG_JavaIllegalArgumentException, msg); return nullreturn; } else


#include "Mach1EncodeCAPI.h"


#ifdef __cplusplus
extern "C" {
#endif

SWIGEXPORT jint JNICALL Java_com_mach1_spatiallibs_Mach1EncodeModuleJNI_Mach1EncodeInputModeMono_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  Mach1EncodeInputModeType result;
  
  (void)jenv;
  (void)jcls;
  result = (Mach1EncodeInputModeType)Mach1EncodeInputModeMono;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_mach1_spatiallibs_Mach1EncodeModuleJNI_Mach1EncodeOutputModeM1Horizon_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  Mach1EncodeOutputModeType result;
  
  (void)jenv;
  (void)jcls;
  result = (Mach1EncodeOutputModeType)Mach1EncodeOutputModeM1Horizon;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_com_mach1_spatiallibs_Mach1EncodeModuleJNI_Mach1EncodeCAPI_1create(JNIEnv *jenv, jclass jcls) {
  jlong jresult = 0 ;
  void *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  result = (void *)Mach1EncodeCAPI_create();
  *(void **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_mach1_spatiallibs_Mach1EncodeModuleJNI_Mach1EncodeCAPI_1delete(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  void *arg1 = (void *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(void **)&jarg1; 
  Mach1EncodeCAPI_delete(arg1);
}


SWIGEXPORT jlong JNICALL Java_com_mach1_spatiallibs_Mach1EncodeModuleJNI_Mach1EncodeCAPI_1getPoints(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jlong jresult = 0 ;
  void *arg1 = (void *) 0 ;
  void *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(void **)&jarg1; 
  result = (void *)Mach1EncodeCAPI_getPoints(arg1);
  *(void **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_com_mach1_spatiallibs_Mach1EncodeModuleJNI_Mach1EncodeCAPI_1getGains(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jlong jresult = 0 ;
  void *arg1 = (void *) 0 ;
  void *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(void **)&jarg1; 
  result = (void *)Mach1EncodeCAPI_getGains(arg1);
  *(void **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_com_mach1_spatiallibs_Mach1EncodeModuleJNI_Mach1EncodeCAPI_1getPointsNames(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jlong jresult = 0 ;
  void *arg1 = (void *) 0 ;
  void *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(void **)&jarg1; 
  result = (void *)Mach1EncodeCAPI_getPointsNames(arg1);
  *(void **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_com_mach1_spatiallibs_Mach1EncodeModuleJNI_Mach1EncodeCAPI_1getGainsForInputChannelNamed(JNIEnv *jenv, jclass jcls, jlong jarg1, jstring jarg2) {
  jlong jresult = 0 ;
  void *arg1 = (void *) 0 ;
  char *arg2 = (char *) 0 ;
  void *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(void **)&jarg1; 
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)jenv->GetStringUTFChars(jarg2, 0);
    if (!arg2) return 0;
  }
  result = (void *)Mach1EncodeCAPI_getGainsForInputChannelNamed(arg1,arg2);
  *(void **)&jresult = result; 
  if (arg2) jenv->ReleaseStringUTFChars(jarg2, (const char *)arg2);
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_mach1_spatiallibs_Mach1EncodeModuleJNI_Mach1EncodeCAPI_1generatePointResults(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  void *arg1 = (void *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(void **)&jarg1; 
  Mach1EncodeCAPI_generatePointResults(arg1);
}


SWIGEXPORT jint JNICALL Java_com_mach1_spatiallibs_Mach1EncodeModuleJNI_Mach1EncodeCAPI_1getPointsCount(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jint jresult = 0 ;
  void *arg1 = (void *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(void **)&jarg1; 
  result = (int)Mach1EncodeCAPI_getPointsCount(arg1);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_com_mach1_spatiallibs_Mach1EncodeModuleJNI_Mach1EncodeCAPI_1getResultingCoeffsDecoded(JNIEnv *jenv, jclass jcls, jlong jarg1, jint jarg2, jlong jarg3) {
  jlong jresult = 0 ;
  void *arg1 = (void *) 0 ;
  enum Mach1DecodeAlgoType arg2 ;
  float *arg3 = (float *) 0 ;
  void *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(void **)&jarg1; 
  arg2 = (enum Mach1DecodeAlgoType)jarg2; 
  arg3 = *(float **)&jarg3; 
  result = (void *)Mach1EncodeCAPI_getResultingCoeffsDecoded(arg1,arg2,arg3);
  *(void **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_com_mach1_spatiallibs_Mach1EncodeModuleJNI_Mach1EncodeCAPI_1getResultingVolumesDecoded(JNIEnv *jenv, jclass jcls, jlong jarg1, jint jarg2, jlong jarg3) {
  jlong jresult = 0 ;
  void *arg1 = (void *) 0 ;
  enum Mach1DecodeAlgoType arg2 ;
  float *arg3 = (float *) 0 ;
  void *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(void **)&jarg1; 
  arg2 = (enum Mach1DecodeAlgoType)jarg2; 
  arg3 = *(float **)&jarg3; 
  result = (void *)Mach1EncodeCAPI_getResultingVolumesDecoded(arg1,arg2,arg3);
  *(void **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_mach1_spatiallibs_Mach1EncodeModuleJNI_Mach1EncodeCAPI_1getInputMode(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jint jresult = 0 ;
  void *arg1 = (void *) 0 ;
  enum Mach1EncodeInputModeType result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(void **)&jarg1; 
  result = (enum Mach1EncodeInputModeType)Mach1EncodeCAPI_getInputMode(arg1);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_mach1_spatiallibs_Mach1EncodeModuleJNI_Mach1EncodeCAPI_1getOutputMode(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jint jresult = 0 ;
  void *arg1 = (void *) 0 ;
  enum Mach1EncodeOutputModeType result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(void **)&jarg1; 
  result = (enum Mach1EncodeOutputModeType)Mach1EncodeCAPI_getOutputMode(arg1);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_mach1_spatiallibs_Mach1EncodeModuleJNI_Mach1EncodeCAPI_1getInputChannelsCount(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jint jresult = 0 ;
  void *arg1 = (void *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(void **)&jarg1; 
  result = (int)Mach1EncodeCAPI_getInputChannelsCount(arg1);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_mach1_spatiallibs_Mach1EncodeModuleJNI_Mach1EncodeCAPI_1getOutputChannelsCount(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jint jresult = 0 ;
  void *arg1 = (void *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(void **)&jarg1; 
  result = (int)Mach1EncodeCAPI_getOutputChannelsCount(arg1);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_mach1_spatiallibs_Mach1EncodeModuleJNI_Mach1EncodeCAPI_1setInputMode(JNIEnv *jenv, jclass jcls, jlong jarg1, jint jarg2) {
  void *arg1 = (void *) 0 ;
  enum Mach1EncodeInputModeType arg2 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(void **)&jarg1; 
  arg2 = (enum Mach1EncodeInputModeType)jarg2; 
  Mach1EncodeCAPI_setInputMode(arg1,arg2);
}


SWIGEXPORT void JNICALL Java_com_mach1_spatiallibs_Mach1EncodeModuleJNI_Mach1EncodeCAPI_1setOutputMode(JNIEnv *jenv, jclass jcls, jlong jarg1, jint jarg2) {
  void *arg1 = (void *) 0 ;
  enum Mach1EncodeOutputModeType arg2 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(void **)&jarg1; 
  arg2 = (enum Mach1EncodeOutputModeType)jarg2; 
  Mach1EncodeCAPI_setOutputMode(arg1,arg2);
}


SWIGEXPORT void JNICALL Java_com_mach1_spatiallibs_Mach1EncodeModuleJNI_Mach1EncodeCAPI_1setRotation(JNIEnv *jenv, jclass jcls, jlong jarg1, jfloat jarg2) {
  void *arg1 = (void *) 0 ;
  float arg2 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(void **)&jarg1; 
  arg2 = (float)jarg2; 
  Mach1EncodeCAPI_setRotation(arg1,arg2);
}


SWIGEXPORT void JNICALL Java_com_mach1_spatiallibs_Mach1EncodeModuleJNI_Mach1EncodeCAPI_1setAzimuth(JNIEnv *jenv, jclass jcls, jlong jarg1, jfloat jarg2) {
  void *arg1 = (void *) 0 ;
  float arg2 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(void **)&jarg1; 
  arg2 = (float)jarg2; 
  Mach1EncodeCAPI_setAzimuth(arg1,arg2);
}


SWIGEXPORT void JNICALL Java_com_mach1_spatiallibs_Mach1EncodeModuleJNI_Mach1EncodeCAPI_1setAzimuthDegrees(JNIEnv *jenv, jclass jcls, jlong jarg1, jfloat jarg2) {
  void *arg1 = (void *) 0 ;
  float arg2 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(void **)&jarg1; 
  arg2 = (float)jarg2; 
  Mach1EncodeCAPI_setAzimuthDegrees(arg1,arg2);
}


SWIGEXPORT void JNICALL Java_com_mach1_spatiallibs_Mach1EncodeModuleJNI_Mach1EncodeCAPI_1setAzimuthRadians(JNIEnv *jenv, jclass jcls, jlong jarg1, jfloat jarg2) {
  void *arg1 = (void *) 0 ;
  float arg2 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(void **)&jarg1; 
  arg2 = (float)jarg2; 
  Mach1EncodeCAPI_setAzimuthRadians(arg1,arg2);
}


SWIGEXPORT void JNICALL Java_com_mach1_spatiallibs_Mach1EncodeModuleJNI_Mach1EncodeCAPI_1setDiverge(JNIEnv *jenv, jclass jcls, jlong jarg1, jfloat jarg2) {
  void *arg1 = (void *) 0 ;
  float arg2 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(void **)&jarg1; 
  arg2 = (float)jarg2; 
  Mach1EncodeCAPI_setDiverge(arg1,arg2);
}


SWIGEXPORT void JNICALL Java_com_mach1_spatiallibs_Mach1EncodeModuleJNI_Mach1EncodeCAPI_1setPitch(JNIEnv *jenv, jclass jcls, jlong jarg1, jfloat jarg2) {
  void *arg1 = (void *) 0 ;
  float arg2 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(void **)&jarg1; 
  arg2 = (float)jarg2; 
  Mach1EncodeCAPI_setPitch(arg1,arg2);
}


SWIGEXPORT void JNICALL Java_com_mach1_spatiallibs_Mach1EncodeModuleJNI_Mach1EncodeCAPI_1setElevation(JNIEnv *jenv, jclass jcls, jlong jarg1, jfloat jarg2) {
  void *arg1 = (void *) 0 ;
  float arg2 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(void **)&jarg1; 
  arg2 = (float)jarg2; 
  Mach1EncodeCAPI_setElevation(arg1,arg2);
}


SWIGEXPORT void JNICALL Java_com_mach1_spatiallibs_Mach1EncodeModuleJNI_Mach1EncodeCAPI_1setElevationDegrees(JNIEnv *jenv, jclass jcls, jlong jarg1, jfloat jarg2) {
  void *arg1 = (void *) 0 ;
  float arg2 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(void **)&jarg1; 
  arg2 = (float)jarg2; 
  Mach1EncodeCAPI_setElevationDegrees(arg1,arg2);
}


SWIGEXPORT void JNICALL Java_com_mach1_spatiallibs_Mach1EncodeModuleJNI_Mach1EncodeCAPI_1setElevationRadians(JNIEnv *jenv, jclass jcls, jlong jarg1, jfloat jarg2) {
  void *arg1 = (void *) 0 ;
  float arg2 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(void **)&jarg1; 
  arg2 = (float)jarg2; 
  Mach1EncodeCAPI_setElevationRadians(arg1,arg2);
}


SWIGEXPORT void JNICALL Java_com_mach1_spatiallibs_Mach1EncodeModuleJNI_Mach1EncodeCAPI_1setIsotropicEncode(JNIEnv *jenv, jclass jcls, jlong jarg1, jboolean jarg2) {
  void *arg1 = (void *) 0 ;
  bool arg2 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(void **)&jarg1; 
  arg2 = jarg2 ? true : false; 
  Mach1EncodeCAPI_setIsotropicEncode(arg1,arg2);
}


SWIGEXPORT void JNICALL Java_com_mach1_spatiallibs_Mach1EncodeModuleJNI_Mach1EncodeCAPI_1setStereoRotate(JNIEnv *jenv, jclass jcls, jlong jarg1, jfloat jarg2) {
  void *arg1 = (void *) 0 ;
  float arg2 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(void **)&jarg1; 
  arg2 = (float)jarg2; 
  Mach1EncodeCAPI_setStereoRotate(arg1,arg2);
}


SWIGEXPORT void JNICALL Java_com_mach1_spatiallibs_Mach1EncodeModuleJNI_Mach1EncodeCAPI_1setOrbitRotation(JNIEnv *jenv, jclass jcls, jlong jarg1, jfloat jarg2) {
  void *arg1 = (void *) 0 ;
  float arg2 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(void **)&jarg1; 
  arg2 = (float)jarg2; 
  Mach1EncodeCAPI_setOrbitRotation(arg1,arg2);
}


SWIGEXPORT void JNICALL Java_com_mach1_spatiallibs_Mach1EncodeModuleJNI_Mach1EncodeCAPI_1setOrbitRotationDegrees(JNIEnv *jenv, jclass jcls, jlong jarg1, jfloat jarg2) {
  void *arg1 = (void *) 0 ;
  float arg2 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(void **)&jarg1; 
  arg2 = (float)jarg2; 
  Mach1EncodeCAPI_setOrbitRotationDegrees(arg1,arg2);
}


SWIGEXPORT void JNICALL Java_com_mach1_spatiallibs_Mach1EncodeModuleJNI_Mach1EncodeCAPI_1setOrbitRotationRadians(JNIEnv *jenv, jclass jcls, jlong jarg1, jfloat jarg2) {
  void *arg1 = (void *) 0 ;
  float arg2 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(void **)&jarg1; 
  arg2 = (float)jarg2; 
  Mach1EncodeCAPI_setOrbitRotationRadians(arg1,arg2);
}


SWIGEXPORT void JNICALL Java_com_mach1_spatiallibs_Mach1EncodeModuleJNI_Mach1EncodeCAPI_1setStereoSpread(JNIEnv *jenv, jclass jcls, jlong jarg1, jfloat jarg2) {
  void *arg1 = (void *) 0 ;
  float arg2 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(void **)&jarg1; 
  arg2 = (float)jarg2; 
  Mach1EncodeCAPI_setStereoSpread(arg1,arg2);
}


SWIGEXPORT void JNICALL Java_com_mach1_spatiallibs_Mach1EncodeModuleJNI_Mach1EncodeCAPI_1setAutoOrbit(JNIEnv *jenv, jclass jcls, jlong jarg1, jboolean jarg2) {
  void *arg1 = (void *) 0 ;
  bool arg2 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(void **)&jarg1; 
  arg2 = jarg2 ? true : false; 
  Mach1EncodeCAPI_setAutoOrbit(arg1,arg2);
}


SWIGEXPORT jint JNICALL Java_com_mach1_spatiallibs_Mach1EncodeModuleJNI_Mach1EncodeCAPI_1getLastCalculationTime(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jint jresult = 0 ;
  void *arg1 = (void *) 0 ;
  long result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(void **)&jarg1; 
  result = (long)Mach1EncodeCAPI_getLastCalculationTime(arg1);
  jresult = (jint)result; 
  return jresult;
}


#ifdef __cplusplus
}
#endif

