/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.mach1.spatiallibs;

public final class Mach1DecodeAlgoType {
  public final static Mach1DecodeAlgoType Mach1DecodeAlgoSpatial_8 = new Mach1DecodeAlgoType("Mach1DecodeAlgoSpatial_8", Mach1DecodeModuleJNI.Mach1DecodeAlgoSpatial_get());
  public final static Mach1DecodeAlgoType Mach1DecodeAlgoHorizon_4 = new Mach1DecodeAlgoType("Mach1DecodeAlgoHorizon_4");
  public final static Mach1DecodeAlgoType Mach1DecodeAlgoHorizonPairs = new Mach1DecodeAlgoType("Mach1DecodeAlgoHorizonPairs");
  public final static Mach1DecodeAlgoType Mach1DecodeAlgoSpatial_12 = new Mach1DecodeAlgoType("Mach1DecodeAlgoSpatial_12");
  public final static Mach1DecodeAlgoType Mach1DecodeAlgoSpatial_14 = new Mach1DecodeAlgoType("Mach1DecodeAlgoSpatial_14");
  public final static Mach1DecodeAlgoType Mach1DecodeAlgoSpatial_18 = new Mach1DecodeAlgoType("Mach1DecodeAlgoSpatial_18");
  public final static Mach1DecodeAlgoType Mach1DecodeAlgoSpatial_22 = new Mach1DecodeAlgoType("Mach1DecodeAlgoSpatial_22");
  public final static Mach1DecodeAlgoType Mach1DecodeAlgoSpatial_32 = new Mach1DecodeAlgoType("Mach1DecodeAlgoSpatial_32");
  public final static Mach1DecodeAlgoType Mach1DecodeAlgoSpatial_36 = new Mach1DecodeAlgoType("Mach1DecodeAlgoSpatial_36");
  public final static Mach1DecodeAlgoType Mach1DecodeAlgoSpatial_48 = new Mach1DecodeAlgoType("Mach1DecodeAlgoSpatial_48");
  public final static Mach1DecodeAlgoType Mach1DecodeAlgoSpatial_60 = new Mach1DecodeAlgoType("Mach1DecodeAlgoSpatial_60");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static Mach1DecodeAlgoType swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + Mach1DecodeAlgoType.class + " with value " + swigValue);
  }

  private Mach1DecodeAlgoType(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private Mach1DecodeAlgoType(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private Mach1DecodeAlgoType(String swigName, Mach1DecodeAlgoType swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static Mach1DecodeAlgoType[] swigValues = { Mach1DecodeAlgoSpatial_8, Mach1DecodeAlgoHorizon_4, Mach1DecodeAlgoHorizonPairs, Mach1DecodeAlgoSpatial_12, Mach1DecodeAlgoSpatial_14, Mach1DecodeAlgoSpatial_18, Mach1DecodeAlgoSpatial_22, Mach1DecodeAlgoSpatial_32, Mach1DecodeAlgoSpatial_36, Mach1DecodeAlgoSpatial_48, Mach1DecodeAlgoSpatial_60 };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

