#!/bin/bash

cp -rf "include/cpp/" "../mach1spatial-libs/arm-chipsets/beaglebone/include"
cp -rf "include/cpp/" "../mach1spatial-libs/arm-chipsets/gcc-arm-cortexm0-cxx14/include"
cp -rf "include/cpp/" "../mach1spatial-libs/arm-chipsets/gcc-armhf-neon-vfpv4/include"
cp -rf "include/cpp/" "../mach1spatial-libs/arm-chipsets/linux-arm/include"
cp -rf "include/cpp/" "../mach1spatial-libs/arm-chipsets/raspberrypi2-cxx11/include"
cp -rf "include/cpp/" "../mach1spatial-libs/arm-chipsets/raspberrypi3-cxx11/include"
cp -rf "include/cpp/" "../mach1spatial-libs/linux/include"
cp -rf "include/cpp/" "../mach1spatial-libs/xcode/include"
cp -rf "include/cpp/" "../mach1spatial-libs/osx-10-13/include"
cp -rf "include/cpp/" "../mach1spatial-libs/vs-15-2017-x86/include"
cp -rf "include/cpp/" "../mach1spatial-libs/vs-15-2017-x86_64/include"
cp -rf "include/cpp/" "../mach1spatial-libs/vs-16-2019-x86/include"
cp -rf "include/cpp/" "../mach1spatial-libs/vs-16-2019-x86_64/include"
cp -rf "include/cpp/" "../mach1spatial-libs/windows-x86/include"
cp -rf "include/cpp/" "../mach1spatial-libs/windows-x86_64/include"
cp -rf "include/java/" "../mach1spatial-libs/android-arm64-v8a/include"
cp -rf "include/java/" "../mach1spatial-libs/android-armeabi-v7a/include"
cp -rf "include/java/" "../mach1spatial-libs/android-x86/include"
cp -rf "include/java/" "../mach1spatial-libs/android-x86_64/include"
cp -rf "include/js/" "../mach1spatial-libs/web"
cp -rf "include/swift/" "../mach1spatial-libs/ios/include"