/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.mach1.Mach1SpatialLibs;

public final class Mach1EncodeOutputModeType {
  public final static Mach1EncodeOutputModeType Mach1EncodeOutputMode4Ch = new Mach1EncodeOutputModeType("Mach1EncodeOutputMode4Ch", Mach1EncodeModuleJNI.Mach1EncodeOutputMode4Ch_get());
  public final static Mach1EncodeOutputModeType Mach1EncodeOutputMode8Ch = new Mach1EncodeOutputModeType("Mach1EncodeOutputMode8Ch", Mach1EncodeModuleJNI.Mach1EncodeOutputMode8Ch_get());

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static Mach1EncodeOutputModeType swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + Mach1EncodeOutputModeType.class + " with value " + swigValue);
  }

  private Mach1EncodeOutputModeType(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private Mach1EncodeOutputModeType(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private Mach1EncodeOutputModeType(String swigName, Mach1EncodeOutputModeType swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static Mach1EncodeOutputModeType[] swigValues = { Mach1EncodeOutputMode4Ch, Mach1EncodeOutputMode8Ch };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

