#!/bin/bash

if [[ "$PWD" == *source ]]
then
	echo "Script called from correct path: $PWD"
	# COPYING INCLUDES
	echo "COPY INCLUDES FOR UE"
	rsync -rc --exclude='*Minified*' --include='*CAPI.h' --exclude='*' "../mach1spatial-libs/xcode/include/" "$(M1SDK_RELEASE_PATH)/mach1spatial-c/Unreal Engine/UE-Mach1SpatialAPI/Mach1DecodePlugin/ThirdParty/Mach1/include"
	rsync -rc --exclude='*Minified*' --exclude='Mach1AudioTimeline.cpp' --include='*.cpp' --exclude='*' "include/cpp/" "$(M1SDK_RELEASE_PATH)/mach1spatial-c/Unreal Engine/UE-Mach1SpatialAPI/Mach1DecodePlugin/Source/Mach1DecodePlugin/Private"
	rsync -rc --exclude='*Minified*' --exclude='*CAPI.h' --exclude='Mach1KeyPoint.h' --exclude='Mach1AudioTimeline.h' --include='*.h' --exclude='*' "include/cpp/" "$(M1SDK_RELEASE_PATH)/mach1spatial-c/Unreal Engine/UE-Mach1SpatialAPI/Mach1DecodePlugin/Source/Mach1DecodePlugin/Public"
	echo "COPY INCLUDES FOR ofxMach1"
	rsync -rc --exclude='*Minified*' --include='*CAPI.h' --exclude='*' "../mach1spatial-libs/xcode/include/" "$(M1SDK_RELEASE_PATH)/mach1spatial-c/openframeworks/ofxMach1/libs/libmach1/include"
	rsync -rc --exclude='*Minified*' --include='*KeyPoint*D.h' --exclude='*' "../mach1spatial-libs/xcode/include/" "$(M1SDK_RELEASE_PATH)/mach1spatial-c/openframeworks/ofxMach1/libs/libmach1/include"
	echo "COPY INCLUDES FOR COCOAPODS"
	rsync -rc "include/swift/" "$(M1SDK_RELEASE_PATH)/mach1spatial-c/ios/Pod-Mach1SpatialAPI/Mach1SpatialAPI/Classes/"
	echo "COPY INCLUDES FOR JITPACK"
	rsync -rc --include='*CAPI.h' --include='*D.h' --include='Mach1Decode.cpp' --include='Mach1Decode.h' --include='' --exclude='*' "include/cpp/" "$(M1SDK_RELEASE_PATH)/mach1spatial-c/android/JitPack-Mach1SpatialAPI/Mach1SpatialLibs/src/main/cpp/mach1/include/"
	rsync -rc "include/java/jni/java/com/mach1/spatiallibs/" "$(M1SDK_RELEASE_PATH)/mach1spatial-c/android/JitPack-Mach1SpatialAPI/Mach1SpatialLibs/src/main/java/com/mach1/spatiallibs"
	rsync -rc --include='*D.h' --exclude='*' "include/cpp/" "$(M1SDK_RELEASE_PATH)/mach1spatial-c/android/JitPack-Mach1SpatialAPI/mach1-decode-example/src/main/cpp"
	echo "COPY LIBS FROM IOS TO EXAMPLES"
	# COPYING FOR UE
	rsync -c "../mach1spatial-libs/ios/lib/libMach1DecodeCAPI.a" "$(M1SDK_RELEASE_PATH)/mach1spatial-c/Unreal Engine/UE-Mach1SpatialAPI/Mach1DecodePlugin/ThirdParty/Mach1/bin/IOS/libMach1DecodeCAPI.a"
	rsync -c "../mach1spatial-libs/ios/lib/libMach1EncodeCAPI.a" "$(M1SDK_RELEASE_PATH)/mach1spatial-c/Unreal Engine/UE-Mach1SpatialAPI/Mach1DecodePlugin/ThirdParty/Mach1/bin/IOS/libMach1EncodeCAPI.a"
	rsync -c "../mach1spatial-libs/ios/lib/libMach1TranscodeCAPI.a" "$(M1SDK_RELEASE_PATH)/mach1spatial-c/Unreal Engine/UE-Mach1SpatialAPI/Mach1DecodePlugin/ThirdParty/Mach1/bin/IOS/libMach1TranscodeCAPI.a"
	rsync -c "../mach1spatial-libs/ios/lib/libMach1DecodePositionalCAPI.a" "$(M1SDK_RELEASE_PATH)/mach1spatial-c/Unreal Engine/UE-Mach1SpatialAPI/Mach1DecodePlugin/ThirdParty/Mach1/bin/IOS/libMach1DecodePositionalCAPI.a"
	# COPYING FOR UNITY
	rsync -c "../mach1spatial-libs/ios/lib/libMach1DecodeCAPI.a" "$(M1SDK_RELEASE_PATH)/mach1spatial-c/Unity/Unity-Mach1SpatialAPI/M1UnityDecodeTest/Assets/Mach1/Plugins/iOS/libMach1DecodeCAPI.a"
	rsync -c "../mach1spatial-libs/ios/lib/libMach1EncodeCAPI.a" "$(M1SDK_RELEASE_PATH)/mach1spatial-c/Unity/Unity-Mach1SpatialAPI/M1UnityDecodeTest/Assets/Mach1/Plugins/iOS/libMach1EncodeCAPI.a"
	rsync -c "../mach1spatial-libs/ios/lib/libMach1TranscodeCAPI.a" "$(M1SDK_RELEASE_PATH)/mach1spatial-c/Unity/Unity-Mach1SpatialAPI/M1UnityDecodeTest/Assets/Mach1/Plugins/iOS/libMach1TranscodeCAPI.a"
	rsync -c "../mach1spatial-libs/ios/lib/libMach1DecodePositionalCAPI.a" "$(M1SDK_RELEASE_PATH)/mach1spatial-c/Unity/Unity-Mach1SpatialAPI/M1UnityDecodeTest/Assets/Mach1/Plugins/iOS/libMach1DecodePositionalCAPI.a"
	# COPYING FOR OFXMACH1
	rsync -c "../mach1spatial-libs/ios/lib/libMach1DecodeCAPI.a" "$(M1SDK_RELEASE_PATH)/mach1spatial-c/openframeworks/ofxMach1/libs/libmach1/lib/ios/libMach1DecodeCAPI.a"
	rsync -c "../mach1spatial-libs/ios/lib/libMach1EncodeCAPI.a" "$(M1SDK_RELEASE_PATH)/mach1spatial-c/openframeworks/ofxMach1/libs/libmach1/lib/ios/libMach1EncodeCAPI.a"
	rsync -c "../mach1spatial-libs/ios/lib/libMach1TranscodeCAPI.a" "$(M1SDK_RELEASE_PATH)/mach1spatial-c/openframeworks/ofxMach1/libs/libmach1/lib/ios/libMach1TranscodeCAPI.a"
	rsync -c "../mach1spatial-libs/ios/lib/libMach1DecodePositionalCAPI.a" "$(M1SDK_RELEASE_PATH)/mach1spatial-c/openframeworks/ofxMach1/libs/libmach1/lib/ios/libMach1DecodePositionalCAPI.a"
	# COPYING FOR COCOAPODS
	rsync -c "../mach1spatial-libs/ios/lib/libMach1DecodeCAPI.a" "$(M1SDK_RELEASE_PATH)/mach1spatial-c/ios/Pod-Mach1SpatialAPI/Mach1SpatialAPI/Lib/ios/libMach1DecodeCAPI.a"
	rsync -c "../mach1spatial-libs/ios/lib/libMach1EncodeCAPI.a" "$(M1SDK_RELEASE_PATH)/mach1spatial-c/ios/Pod-Mach1SpatialAPI/Mach1SpatialAPI/Lib/ios/libMach1EncodeCAPI.a"
	rsync -c "../mach1spatial-libs/ios/lib/libMach1TranscodeCAPI.a" "$(M1SDK_RELEASE_PATH)/mach1spatial-c/ios/Pod-Mach1SpatialAPI/Mach1SpatialAPI/Lib/ios/libMach1TranscodeCAPI.a"
	rsync -c "../mach1spatial-libs/ios/lib/libMach1DecodePositionalCAPI.a" "$(M1SDK_RELEASE_PATH)/mach1spatial-c/ios/Pod-Mach1SpatialAPI/Mach1SpatialAPI/Lib/ios/libMach1DecodePositionalCAPI.a"
	echo "COPY LIBS FROM ANDROID TO EXAMPLES"
	# COPYING FOR UNITY
	rsync -c "../mach1spatial-libs/android-armeabi-v7a/lib-shared/libMach1DecodeCAPI.so" "$(M1SDK_RELEASE_PATH)/mach1spatial-c/Unity/Unity-Mach1SpatialAPI/M1UnityDecodeTest/Assets/Mach1/Plugins/Android/armeabi-v7a/libMach1DecodeCAPI.so" 
	rsync -c "../mach1spatial-libs/android-armeabi-v7a/lib-shared/libMach1EncodeCAPI.so" "$(M1SDK_RELEASE_PATH)/mach1spatial-c/Unity/Unity-Mach1SpatialAPI/M1UnityDecodeTest/Assets/Mach1/Plugins/Android/armeabi-v7a/libMach1EncodeCAPI.so"
	rsync -c "../mach1spatial-libs/android-armeabi-v7a/lib-shared/libMach1TranscodeCAPI.so" "$(M1SDK_RELEASE_PATH)/mach1spatial-c/Unity/Unity-Mach1SpatialAPI/M1UnityDecodeTest/Assets/Mach1/Plugins/Android/armeabi-v7a/libMach1TranscodeCAPI.so"
	rsync -c "../mach1spatial-libs/android-armeabi-v7a/lib-shared/libMach1DecodePositionalCAPI.so" "$(M1SDK_RELEASE_PATH)/mach1spatial-c/Unity/Unity-Mach1SpatialAPI/M1UnityDecodeTest/Assets/Mach1/Plugins/Android/armeabi-v7a/libMach1DecodePositionalCAPI.so"
	rsync -c "../mach1spatial-libs/android-arm64-v8a/lib-shared/libMach1DecodeCAPI.so" "$(M1SDK_RELEASE_PATH)/mach1spatial-c/Unity/Unity-Mach1SpatialAPI/M1UnityDecodeTest/Assets/Mach1/Plugins/Android/arm64-v8a/libMach1DecodeCAPI.so"
	rsync -c "../mach1spatial-libs/android-arm64-v8a/lib-shared/libMach1EncodeCAPI.so" "$(M1SDK_RELEASE_PATH)/mach1spatial-c/Unity/Unity-Mach1SpatialAPI/M1UnityDecodeTest/Assets/Mach1/Plugins/Android/arm64-v8a/libMach1EncodeCAPI.so"
	rsync -c "../mach1spatial-libs/android-arm64-v8a/lib-shared/libMach1TranscodeCAPI.so" "$(M1SDK_RELEASE_PATH)/mach1spatial-c/Unity/Unity-Mach1SpatialAPI/M1UnityDecodeTest/Assets/Mach1/Plugins/Android/arm64-v8a/libMach1TranscodeCAPI.so"
	rsync -c "../mach1spatial-libs/android-arm64-v8a/lib-shared/libMach1DecodePositionalCAPI.so" "$(M1SDK_RELEASE_PATH)/mach1spatial-c/Unity/Unity-Mach1SpatialAPI/M1UnityDecodeTest/Assets/Mach1/Plugins/Android/arm64-v8a/libMach1DecodePositionalCAPI.so"
	rsync -c "../mach1spatial-libs/android-x86/lib-shared/libMach1DecodeCAPI.so" "$(M1SDK_RELEASE_PATH)/mach1spatial-c/Unity/Unity-Mach1SpatialAPI/M1UnityDecodeTest/Assets/Mach1/Plugins/Android/x86/libMach1DecodeCAPI.so"
	rsync -c "../mach1spatial-libs/android-x86/lib-shared/libMach1EncodeCAPI.so" "$(M1SDK_RELEASE_PATH)/mach1spatial-c/Unity/Unity-Mach1SpatialAPI/M1UnityDecodeTest/Assets/Mach1/Plugins/Android/x86/libMach1EncodeCAPI.so"
	rsync -c "../mach1spatial-libs/android-x86/lib-shared/libMach1TranscodeCAPI.so" "$(M1SDK_RELEASE_PATH)/mach1spatial-c/Unity/Unity-Mach1SpatialAPI/M1UnityDecodeTest/Assets/Mach1/Plugins/Android/x86/libMach1TranscodeCAPI.so"
	rsync -c "../mach1spatial-libs/android-x86/lib-shared/libMach1DecodePositionalCAPI.so" "$(M1SDK_RELEASE_PATH)/mach1spatial-c/Unity/Unity-Mach1SpatialAPI/M1UnityDecodeTest/Assets/Mach1/Plugins/Android/x86/libMach1DecodePositionalCAPI.so"
	rsync -c "../mach1spatial-libs/android-x86_64/lib-shared/libMach1DecodeCAPI.so" "$(M1SDK_RELEASE_PATH)/mach1spatial-c/Unity/Unity-Mach1SpatialAPI/M1UnityDecodeTest/Assets/Mach1/Plugins/Android/x86_64/libMach1DecodeCAPI.so"
	rsync -c "../mach1spatial-libs/android-x86_64/lib-shared/libMach1EncodeCAPI.so" "$(M1SDK_RELEASE_PATH)/mach1spatial-c/Unity/Unity-Mach1SpatialAPI/M1UnityDecodeTest/Assets/Mach1/Plugins/Android/x86_64/libMach1EncodeCAPI.so"
	rsync -c "../mach1spatial-libs/android-x86_64/lib-shared/libMach1TranscodeCAPI.so" "$(M1SDK_RELEASE_PATH)/mach1spatial-c/Unity/Unity-Mach1SpatialAPI/M1UnityDecodeTest/Assets/Mach1/Plugins/Android/x86_64/libMach1TranscodeCAPI.so"
	rsync -c "../mach1spatial-libs/android-x86_64/lib-shared/libMach1DecodePositionalCAPI.so" "$(M1SDK_RELEASE_PATH)/mach1spatial-c/Unity/Unity-Mach1SpatialAPI/M1UnityDecodeTest/Assets/Mach1/Plugins/Android/x86_64/libMach1DecodePositionalCAPI.so"
	rsync -c "../mach1spatial-libs/android-armeabi-v7a/lib-shared/libMach1DecodeCAPI.so" "$(M1SDK_RELEASE_PATH)/mach1spatial-c/Unity/Unity-Mach1SpatialAPI/M1DSPGraph/Assets/Mach1/Plugins/Android/armeabi-v7a/libMach1DecodeCAPI.so"
	rsync -c "../mach1spatial-libs/android-armeabi-v7a/lib-shared/libMach1EncodeCAPI.so" "$(M1SDK_RELEASE_PATH)/mach1spatial-c/Unity/Unity-Mach1SpatialAPI/M1DSPGraph/Assets/Mach1/Plugins/Android/armeabi-v7a/libMach1EncodeCAPI.so"
	rsync -c "../mach1spatial-libs/android-armeabi-v7a/lib-shared/libMach1TranscodeCAPI.so" "$(M1SDK_RELEASE_PATH)/mach1spatial-c/Unity/Unity-Mach1SpatialAPI/M1DSPGraph/Assets/Mach1/Plugins/Android/armeabi-v7a/libMach1TranscodeCAPI.so"
	rsync -c "../mach1spatial-libs/android-armeabi-v7a/lib-shared/libMach1DecodePositionalCAPI.so" "$(M1SDK_RELEASE_PATH)/mach1spatial-c/Unity/Unity-Mach1SpatialAPI/M1DSPGraph/Assets/Mach1/Plugins/Android/armeabi-v7a/libMach1DecodePositionalCAPI.so"
	rsync -c "../mach1spatial-libs/android-arm64-v8a/lib-shared/libMach1DecodeCAPI.so" "$(M1SDK_RELEASE_PATH)/mach1spatial-c/Unity/Unity-Mach1SpatialAPI/M1DSPGraph/Assets/Mach1/Plugins/Android/arm64-v8a/libMach1DecodeCAPI.so"
	rsync -c "../mach1spatial-libs/android-arm64-v8a/lib-shared/libMach1EncodeCAPI.so" "$(M1SDK_RELEASE_PATH)/mach1spatial-c/Unity/Unity-Mach1SpatialAPI/M1DSPGraph/Assets/Mach1/Plugins/Android/arm64-v8a/libMach1EncodeCAPI.so"
	rsync -c "../mach1spatial-libs/android-arm64-v8a/lib-shared/libMach1TranscodeCAPI.so" "$(M1SDK_RELEASE_PATH)/mach1spatial-c/Unity/Unity-Mach1SpatialAPI/M1DSPGraph/Assets/Mach1/Plugins/Android/arm64-v8a/libMach1TranscodeCAPI.so"
	rsync -c "../mach1spatial-libs/android-arm64-v8a/lib-shared/libMach1DecodePositionalCAPI.so" "$(M1SDK_RELEASE_PATH)/mach1spatial-c/Unity/Unity-Mach1SpatialAPI/M1DSPGraph/Assets/Mach1/Plugins/Android/arm64-v8a/libMach1DecodePositionalCAPI.so"
	rsync -c "../mach1spatial-libs/android-x86/lib-shared/libMach1DecodeCAPI.so" "$(M1SDK_RELEASE_PATH)/mach1spatial-c/Unity/Unity-Mach1SpatialAPI/M1DSPGraph/Assets/Mach1/Plugins/Android/x86/libMach1DecodeCAPI.so"
	rsync -c "../mach1spatial-libs/android-x86/lib-shared/libMach1EncodeCAPI.so" "$(M1SDK_RELEASE_PATH)/mach1spatial-c/Unity/Unity-Mach1SpatialAPI/M1DSPGraph/Assets/Mach1/Plugins/Android/x86/libMach1EncodeCAPI.so"
	rsync -c "../mach1spatial-libs/android-x86/lib-shared/libMach1TranscodeCAPI.so" "$(M1SDK_RELEASE_PATH)/mach1spatial-c/Unity/Unity-Mach1SpatialAPI/M1DSPGraph/Assets/Mach1/Plugins/Android/x86/libMach1TranscodeCAPI.so"
	rsync -c "../mach1spatial-libs/android-x86/lib-shared/libMach1DecodePositionalCAPI.so" "$(M1SDK_RELEASE_PATH)/mach1spatial-c/Unity/Unity-Mach1SpatialAPI/M1DSPGraph/Assets/Mach1/Plugins/Android/x86/libMach1DecodePositionalCAPI.so"
	rsync -c "../mach1spatial-libs/android-x86_64/lib-shared/libMach1DecodeCAPI.so" "$(M1SDK_RELEASE_PATH)/mach1spatial-c/Unity/Unity-Mach1SpatialAPI/M1DSPGraph/Assets/Mach1/Plugins/Android/x86_64/libMach1DecodeCAPI.so"
	rsync -c "../mach1spatial-libs/android-x86_64/lib-shared/libMach1EncodeCAPI.so" "$(M1SDK_RELEASE_PATH)/mach1spatial-c/Unity/Unity-Mach1SpatialAPI/M1DSPGraph/Assets/Mach1/Plugins/Android/x86_64/libMach1EncodeCAPI.so"
	rsync -c "../mach1spatial-libs/android-x86_64/lib-shared/libMach1TranscodeCAPI.so" "$(M1SDK_RELEASE_PATH)/mach1spatial-c/Unity/Unity-Mach1SpatialAPI/M1DSPGraph/Assets/Mach1/Plugins/Android/x86_64/libMach1TranscodeCAPI.so"
	rsync -c "../mach1spatial-libs/android-x86_64/lib-shared/libMach1DecodePositionalCAPI.so" "$(M1SDK_RELEASE_PATH)/mach1spatial-c/Unity/Unity-Mach1SpatialAPI/M1DSPGraph/Assets/Mach1/Plugins/Android/x86_64/libMach1DecodePositionalCAPI.so"
	# COPYING FOR UE
	rsync -c "../mach1spatial-libs/android-armeabi-v7a/lib/libMach1DecodeCAPI.a" "$(M1SDK_RELEASE_PATH)/mach1spatial-c/Unreal Engine/UE-Mach1SpatialAPI/Mach1DecodePlugin/ThirdParty/Mach1/bin/Android/armeabi-v7a/libMach1DecodeCAPI.a"
	rsync -c "../mach1spatial-libs/android-armeabi-v7a/lib/libMach1EncodeCAPI.a" "$(M1SDK_RELEASE_PATH)/mach1spatial-c/Unreal Engine/UE-Mach1SpatialAPI/Mach1DecodePlugin/ThirdParty/Mach1/bin/Android/armeabi-v7a/libMach1EncodeCAPI.a"
	rsync -c "../mach1spatial-libs/android-armeabi-v7a/lib/libMach1TranscodeCAPI.a" "$(M1SDK_RELEASE_PATH)/mach1spatial-c/Unreal Engine/UE-Mach1SpatialAPI/Mach1DecodePlugin/ThirdParty/Mach1/bin/Android/armeabi-v7a/libMach1TranscodeCAPI.a"
	rsync -c "../mach1spatial-libs/android-armeabi-v7a/lib/libMach1DecodePositionalCAPI.a" "$(M1SDK_RELEASE_PATH)/mach1spatial-c/Unreal Engine/UE-Mach1SpatialAPI/Mach1DecodePlugin/ThirdParty/Mach1/bin/Android/armeabi-v7a/libMach1DecodePositionalCAPI.a"
	rsync -c "../mach1spatial-libs/android-x86/lib/libMach1DecodeCAPI.a" "$(M1SDK_RELEASE_PATH)/mach1spatial-c/Unreal Engine/UE-Mach1SpatialAPI/Mach1DecodePlugin/ThirdParty/Mach1/bin/Android/x86/libMach1DecodeCAPI.a"
	rsync -c "../mach1spatial-libs/android-x86/lib/libMach1EncodeCAPI.a" "$(M1SDK_RELEASE_PATH)/mach1spatial-c/Unreal Engine/UE-Mach1SpatialAPI/Mach1DecodePlugin/ThirdParty/Mach1/bin/Android/x86/libMach1EncodeCAPI.a"
	rsync -c "../mach1spatial-libs/android-x86/lib/libMach1TranscodeCAPI.a" "$(M1SDK_RELEASE_PATH)/mach1spatial-c/Unreal Engine/UE-Mach1SpatialAPI/Mach1DecodePlugin/ThirdParty/Mach1/bin/Android/x86/libMach1TranscodeCAPI.a"
	rsync -c "../mach1spatial-libs/android-x86/lib/libMach1DecodePositionalCAPI.a" "$(M1SDK_RELEASE_PATH)/mach1spatial-c/Unreal Engine/UE-Mach1SpatialAPI/Mach1DecodePlugin/ThirdParty/Mach1/bin/Android/x86/libMach1DecodePositionalCAPI.a"
	# COPYING FOR OFXMACH1
	rsync -c "../mach1spatial-libs/android-armeabi-v7a/lib/libMach1DecodeCAPI.a" "$(M1SDK_RELEASE_PATH)/mach1spatial-c/openframeworks/ofxMach1/libs/libmach1/lib/android/armeabi-v7a/libMach1DecodeCAPI.a"
	rsync -c "../mach1spatial-libs/android-armeabi-v7a/lib/libMach1EncodeCAPI.a" "$(M1SDK_RELEASE_PATH)/mach1spatial-c/openframeworks/ofxMach1/libs/libmach1/lib/android/armeabi-v7a/libMach1EncodeCAPI.a"
	rsync -c "../mach1spatial-libs/android-armeabi-v7a/lib/libMach1TranscodeCAPI.a" "$(M1SDK_RELEASE_PATH)/mach1spatial-c/openframeworks/ofxMach1/libs/libmach1/lib/android/armeabi-v7a/libMach1TranscodeCAPI.a"
	rsync -c "../mach1spatial-libs/android-armeabi-v7a/lib/libMach1DecodePositionalCAPI.a" "$(M1SDK_RELEASE_PATH)/mach1spatial-c/openframeworks/ofxMach1/libs/libmach1/lib/android/armeabi-v7a/libMach1DecodePositionalCAPI.a"
	rsync -c "../mach1spatial-libs/android-x86/lib/libMach1DecodeCAPI.a" "$(M1SDK_RELEASE_PATH)/mach1spatial-c/openframeworks/ofxMach1/libs/libmach1/lib/android/x86/libMach1DecodeCAPI.a"
	rsync -c "../mach1spatial-libs/android-x86/lib/libMach1EncodeCAPI.a" "$(M1SDK_RELEASE_PATH)/mach1spatial-c/openframeworks/ofxMach1/libs/libmach1/lib/android/x86/libMach1EncodeCAPI.a"
	rsync -c "../mach1spatial-libs/android-x86/lib/libMach1TranscodeCAPI.a" "$(M1SDK_RELEASE_PATH)/mach1spatial-c/openframeworks/ofxMach1/libs/libmach1/lib/android/x86/libMach1TranscodeCAPI.a"
	rsync -c "../mach1spatial-libs/android-x86/lib/libMach1DecodePositionalCAPI.a" "$(M1SDK_RELEASE_PATH)/mach1spatial-c/openframeworks/ofxMach1/libs/libmach1/lib/android/x86/libMach1DecodePositionalCAPI.a"
	# COPYING FOR JITPACK
	rsync -c "../mach1spatial-libs/android-armeabi-v7a/lib/libMach1DecodeCAPI.a" "$(M1SDK_RELEASE_PATH)/mach1spatial-c/android/JitPack-Mach1SpatialAPI/Mach1SpatialLibs/src/main/jniLibs/armeabi-v7a/libMach1DecodeCAPI.a"
	rsync -c "../mach1spatial-libs/android-armeabi-v7a/lib/libMach1EncodeCAPI.a" "$(M1SDK_RELEASE_PATH)/mach1spatial-c/android/JitPack-Mach1SpatialAPI/Mach1SpatialLibs/src/main/jniLibs/armeabi-v7a/libMach1EncodeCAPI.a"
	rsync -c "../mach1spatial-libs/android-armeabi-v7a/lib/libMach1TranscodeCAPI.a" "$(M1SDK_RELEASE_PATH)/mach1spatial-c/android/JitPack-Mach1SpatialAPI/Mach1SpatialLibs/src/main/jniLibs/armeabi-v7a/libMach1TranscodeCAPI.a"
	rsync -c "../mach1spatial-libs/android-armeabi-v7a/lib/libMach1DecodePositionalCAPI.a" "$(M1SDK_RELEASE_PATH)/mach1spatial-c/android/JitPack-Mach1SpatialAPI/Mach1SpatialLibs/src/main/jniLibs/armeabi-v7a/libMach1DecodePositionalCAPI.a"
	rsync -c "../mach1spatial-libs/android-arm64-v8a/lib/libMach1DecodeCAPI.a" "$(M1SDK_RELEASE_PATH)/mach1spatial-c/android/JitPack-Mach1SpatialAPI/Mach1SpatialLibs/src/main/jniLibs/arm64-v8a/libMach1DecodeCAPI.a"
	rsync -c "../mach1spatial-libs/android-arm64-v8a/lib/libMach1EncodeCAPI.a" "$(M1SDK_RELEASE_PATH)/mach1spatial-c/android/JitPack-Mach1SpatialAPI/Mach1SpatialLibs/src/main/jniLibs/arm64-v8a/libMach1EncodeCAPI.a"
	rsync -c "../mach1spatial-libs/android-arm64-v8a/lib/libMach1TranscodeCAPI.a" "$(M1SDK_RELEASE_PATH)/mach1spatial-c/android/JitPack-Mach1SpatialAPI/Mach1SpatialLibs/src/main/jniLibs/arm64-v8a/libMach1TranscodeCAPI.a"
	rsync -c "../mach1spatial-libs/android-arm64-v8a/lib/libMach1DecodePositionalCAPI.a" "$(M1SDK_RELEASE_PATH)/mach1spatial-c/android/JitPack-Mach1SpatialAPI/Mach1SpatialLibs/src/main/jniLibs/arm64-v8a/libMach1DecodePositionalCAPI.a"
	rsync -c "../mach1spatial-libs/android-x86/lib/libMach1DecodeCAPI.a" "$(M1SDK_RELEASE_PATH)/mach1spatial-c/android/JitPack-Mach1SpatialAPI/Mach1SpatialLibs/src/main/jniLibs/x86/libMach1DecodeCAPI.a"
	rsync -c "../mach1spatial-libs/android-x86/lib/libMach1EncodeCAPI.a" "$(M1SDK_RELEASE_PATH)/mach1spatial-c/android/JitPack-Mach1SpatialAPI/Mach1SpatialLibs/src/main/jniLibs/x86/libMach1EncodeCAPI.a"
	rsync -c "../mach1spatial-libs/android-x86/lib/libMach1TranscodeCAPI.a" "$(M1SDK_RELEASE_PATH)/mach1spatial-c/android/JitPack-Mach1SpatialAPI/Mach1SpatialLibs/src/main/jniLibs/x86/libMach1TranscodeCAPI.a"
	rsync -c "../mach1spatial-libs/android-x86/lib/libMach1DecodePositionalCAPI.a" "$(M1SDK_RELEASE_PATH)/mach1spatial-c/android/JitPack-Mach1SpatialAPI/Mach1SpatialLibs/src/main/jniLibs/x86/libMach1DecodePositionalCAPI.a"
	rsync -c "../mach1spatial-libs/android-x86_64/lib/libMach1DecodeCAPI.a" "$(M1SDK_RELEASE_PATH)/mach1spatial-c/android/JitPack-Mach1SpatialAPI/Mach1SpatialLibs/src/main/jniLibs/x86_64/libMach1DecodeCAPI.a"
	rsync -c "../mach1spatial-libs/android-x86_64/lib/libMach1EncodeCAPI.a" "$(M1SDK_RELEASE_PATH)/mach1spatial-c/android/JitPack-Mach1SpatialAPI/Mach1SpatialLibs/src/main/jniLibs/x86_64/libMach1EncodeCAPI.a"
	rsync -c "../mach1spatial-libs/android-x86_64/lib/libMach1TranscodeCAPI.a" "$(M1SDK_RELEASE_PATH)/mach1spatial-c/android/JitPack-Mach1SpatialAPI/Mach1SpatialLibs/src/main/jniLibs/x86_64/libMach1TranscodeCAPI.a"
	rsync -c "../mach1spatial-libs/android-x86_64/lib/libMach1DecodePositionalCAPI.a" "$(M1SDK_RELEASE_PATH)/mach1spatial-c/android/JitPack-Mach1SpatialAPI/Mach1SpatialLibs/src/main/jniLibs/x86_64/libMach1DecodePositionalCAPI.a"        
	# COPYING SINGLE DECODE LIB FOR OLD ANDROID EXAMPLE
	rsync -c "../mach1spatial-libs/android-armeabi-v7a/lib/libMach1DecodeCAPI.a" "$(M1SDK_RELEASE_PATH)/mach1spatial-c/android/JitPack-Mach1SpatialAPI/mach1-decode-example/src/main/jniLibs/armeabi-v7a/libMach1DecodeCAPI.a"
	echo "COPY LIBS FROM LINUX TO EXAMPLES"
	# COPYING FOR OFXMACH1
	mkdir -p $(M1SDK_RELEASE_PATH)/mach1spatial-c/openframeworks/ofxMach1/libs/libmach1/lib/linux
	rsync -c "../mach1spatial-libs/linux/lib/libMach1DecodeCAPI.a" "$(M1SDK_RELEASE_PATH)/mach1spatial-c/openframeworks/ofxMach1/libs/libmach1/lib/linux/libMach1DecodeCAPI.a"
	rsync -c "../mach1spatial-libs/linux/lib/libMach1EncodeCAPI.a" "$(M1SDK_RELEASE_PATH)/mach1spatial-c/openframeworks/ofxMach1/libs/libmach1/lib/linux/libMach1EncodeCAPI.a"
	rsync -c "../mach1spatial-libs/linux/lib/libMach1TranscodeCAPI.a" "$(M1SDK_RELEASE_PATH)/mach1spatial-c/openframeworks/ofxMach1/libs/libmach1/lib/linux/libMach1TranscodeCAPI.a"
	rsync -c "../mach1spatial-libs/linux/lib/libMach1DecodePositionalCAPI.a" "$(M1SDK_RELEASE_PATH)/mach1spatial-c/openframeworks/ofxMach1/libs/libmach1/lib/linux/libMach1DecodePositionalCAPI.a"
	# COPYING FOR UNITY
	mkdir -p $(M1SDK_RELEASE_PATH)/mach1spatial-c/Unity/Unity-Mach1SpatialAPI/M1UnityDecodeTest/Assets/Mach1/Plugins/Linux
	mkdir -p $(M1SDK_RELEASE_PATH)/mach1spatial-c/Unity/Unity-Mach1SpatialAPI/M1DSPGraph/Assets/Mach1/Plugins/Linux
	# rsync -c "_install/gcc/lib-shared" "$(M1SDK_RELEASE_PATH)/mach1spatial-c/Unity/Unity-Mach1SpatialAPI/M1UnityDecodeTest/Assets/Mach1/Plugins/Linux/"
	# rsync -c "_install/gcc/lib-shared" "$(M1SDK_RELEASE_PATH)/mach1spatial-c/Unity/Unity-Mach1SpatialAPI/M1DSPGraph/Assets/Mach1/Plugins/Linux/"
	echo "COPY LIBS FROM MACOS TO EXAMPLES"
	# COPYING FOR UE
	rsync -c "../mach1spatial-libs/xcode/lib/libMach1DecodeCAPI.a" "$(M1SDK_RELEASE_PATH)/mach1spatial-c/Unreal Engine/UE-Mach1SpatialAPI/Mach1DecodePlugin/ThirdParty/Mach1/bin/Mac/libMach1DecodeCAPI.a"
	rsync -c "../mach1spatial-libs/xcode/lib/libMach1EncodeCAPI.a" "$(M1SDK_RELEASE_PATH)/mach1spatial-c/Unreal Engine/UE-Mach1SpatialAPI/Mach1DecodePlugin/ThirdParty/Mach1/bin/Mac/libMach1EncodeCAPI.a"
	rsync -c "../mach1spatial-libs/xcode/lib/libMach1TranscodeCAPI.a" "$(M1SDK_RELEASE_PATH)/mach1spatial-c/Unreal Engine/UE-Mach1SpatialAPI/Mach1DecodePlugin/ThirdParty/Mach1/bin/Mac/libMach1TranscodeCAPI.a"
	rsync -c "../mach1spatial-libs/xcode/lib/libMach1DecodePositionalCAPI.a" "$(M1SDK_RELEASE_PATH)/mach1spatial-c/Unreal Engine/UE-Mach1SpatialAPI/Mach1DecodePlugin/ThirdParty/Mach1/bin/Mac/libMach1DecodePositionalCAPI.a"
	# COPYING FOR UNITY
	rsync -rc "../mach1spatial-libs/xcode/lib-bundle/" "$(M1SDK_RELEASE_PATH)/mach1spatial-c/Unity/Unity-Mach1SpatialAPI/M1UnityDecodeTest/Assets/Mach1/Plugins/macOS/"
	rsync -rc "../mach1spatial-libs/xcode/lib-bundle/" "$(M1SDK_RELEASE_PATH)/mach1spatial-c/Unity/Unity-Mach1SpatialAPI/M1DSPGraph/Assets/Mach1/Plugins/macOS/"
	# COPYING FOR OFXMACH1
	rsync -c "../mach1spatial-libs/xcode/lib/libMach1DecodeCAPI.a" "$(M1SDK_RELEASE_PATH)/mach1spatial-c/openframeworks/ofxMach1/libs/libmach1/lib/osx/libMach1DecodeCAPI.a"
	rsync -c "../mach1spatial-libs/xcode/lib/libMach1EncodeCAPI.a" "$(M1SDK_RELEASE_PATH)/mach1spatial-c/openframeworks/ofxMach1/libs/libmach1/lib/osx/libMach1EncodeCAPI.a"
	rsync -c "../mach1spatial-libs/xcode/lib/libMach1TranscodeCAPI.a" "$(M1SDK_RELEASE_PATH)/mach1spatial-c/openframeworks/ofxMach1/libs/libmach1/lib/osx/libMach1TranscodeCAPI.a"
	rsync -c "../mach1spatial-libs/xcode/lib/libMach1DecodePositionalCAPI.a" "$(M1SDK_RELEASE_PATH)/mach1spatial-c/openframeworks/ofxMach1/libs/libmach1/lib/osx/libMach1DecodePositionalCAPI.a"
	echo "COPY LIBS FROM WEB TO EXAMPLES"
	# NODEJS
	rsync -c "../mach1spatial-libs/web/Mach1Decode.js" "$(M1SDK_RELEASE_PATH)/mach1spatial-nodejs/mach1spatial-decode/lib/Mach1Decode.js"
	rsync -c "../mach1spatial-libs/web/Mach1Decode.wasm" "$(M1SDK_RELEASE_PATH)/mach1spatial-nodejs/mach1spatial-decode/lib/Mach1Decode.wasm"
	rsync -c "../mach1spatial-libs/web/Mach1DecodePositional.js" "$(M1SDK_RELEASE_PATH)/mach1spatial-nodejs/mach1spatial-decode/lib/Mach1DecodePositional.js"
	rsync -c "../mach1spatial-libs/web/Mach1DecodePositional.wasm" "$(M1SDK_RELEASE_PATH)/mach1spatial-nodejs/mach1spatial-decode/lib/Mach1DecodePositional.wasm"
	rsync -c "../mach1spatial-libs/web/Mach1Encode.js" "$(M1SDK_RELEASE_PATH)/mach1spatial-nodejs/mach1spatial-encode/lib/Mach1Encode.js"
	rsync -c "../mach1spatial-libs/web/Mach1Encode.wasm" "$(M1SDK_RELEASE_PATH)/mach1spatial-nodejs/mach1spatial-encode/lib/Mach1Encode.wasm"
	rsync -c "../mach1spatial-libs/web/Mach1Transcode.js" "$(M1SDK_RELEASE_PATH)/mach1spatial-nodejs/mach1spatial-transcode/lib/Mach1Transcode.js"
	rsync -c "../mach1spatial-libs/web/Mach1Transcode.wasm" "$(M1SDK_RELEASE_PATH)/mach1spatial-nodejs/mach1spatial-transcode/lib/Mach1Transcode.wasm"
	# EXAMPLES
	rsync -c ../mach1spatial-libs/web/* $(M1SDK_RELEASE_PATH)/mach1spatial-web/js
	rsync -c "../mach1spatial-libs/web/Mach1Decode.js" "$(M1SDK_RELEASE_PATH)/mach1spatial-web/m1-web-spatialaudioplayer/js/Mach1Decode.js"
	rsync -c "../mach1spatial-libs/web/Mach1Decode.wasm" "$(M1SDK_RELEASE_PATH)/mach1spatial-web/m1-web-spatialaudioplayer/js/Mach1Decode.wasm"
	# OFXMACH1
	rsync -c ../mach1spatial-libs/web/* $(M1SDK_RELEASE_PATH)/mach1spatial-c/openframeworks/ofxMach1/libs/libmach1/lib/emscripten/
	echo "COPY LIBS FROM WINDOWS TO EXAMPLES"
	# x86
	rsync -c --exclude='*.lib' --include='*.dll' "../mach1spatial-libs/vs-15-2017-x86/lib/Dynamic/Release" "$(M1SDK_RELEASE_PATH)/mach1spatial-c/Unity/Unity-Mach1SpatialAPI/M1UnityDecodeTest/Assets/Mach1/Plugins/Windows/x86"
	rsync -c --exclude='*.lib' --include='*.dll' "../mach1spatial-libs/vs-15-2017-x86/lib/Dynamic/Release" "$(M1SDK_RELEASE_PATH)/mach1spatial-c/Unity/Unity-Mach1SpatialAPI/M1DSPGraph/Assets/Mach1/Plugins/Windows/x86"
	# rsync -c "../mach1spatial-libs/vs-15-2017-x86/lib/Static/MD/Release" "$(M1SDK_RELEASE_PATH)/mach1spatial-c/Unreal Engine/UE-Mach1SpatialAPI/Mach1DecodePlugin/ThirdParty/Mach1/bin/Win32"
	rsync -c "../mach1spatial-libs/vs-15-2017-x86/lib/Static/MD/Release" "$(M1SDK_RELEASE_PATH)/mach1spatial-c/openframeworks/ofxMach1/libs/libmach1/lib/vs/x86"
	# x64
	rsync -c --exclude='*.lib' --include='*.dll' "../mach1spatial-libs/vs-15-2017-x86_64/lib/Dynamic/Release" "$(M1SDK_RELEASE_PATH)/mach1spatial-c/Unity/Unity-Mach1SpatialAPI/M1UnityDecodeTest/Assets/Mach1/Plugins/Windows/x86_64"
	rsync -c --exclude='*.lib' --include='*.dll' "../mach1spatial-libs/vs-15-2017-x86_64/lib/Dynamic/Release" "$(M1SDK_RELEASE_PATH)/mach1spatial-c/Unity/Unity-Mach1SpatialAPI/M1DSPGraph/Assets/Mach1/Plugins/Windows/x86_64"
	rsync -c --exclude='*inified*' --exclude='*Encode*' --exclude='*Transcode*' --exclude='*d.*' "../mach1spatial-libs/vs-15-2017-x86_64/lib/Static/MD/Release" "$(M1SDK_RELEASE_PATH)/mach1spatial-c/Unreal Engine/UE-Mach1SpatialAPI/Mach1DecodePlugin/ThirdParty/Mach1/bin/Win64"
	rsync -c --exclude='*inified*' --exclude='*Encode*' --exclude='*Transcode*' --exclude='*d.*' "../mach1spatial-libs/vs-15-2017-x86_64/lib/Static/MD/Release" "$(M1SDK_RELEASE_PATH)/mach1spatial-c/openframeworks/ofxMach1/libs/libmach1/lib/vs/x64"
else
	echo "ERROR: Script called from wrong directory: $PWD"
fi