/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.mach1.spatiallibs;

public final class Mach1PlatformType {
  public final static Mach1PlatformType Mach1PlatformDefault = new Mach1PlatformType("Mach1PlatformDefault", Mach1DecodeModuleJNI.Mach1PlatformDefault_get());
  public final static Mach1PlatformType Mach1PlatformUnity = new Mach1PlatformType("Mach1PlatformUnity");
  public final static Mach1PlatformType Mach1PlatformUE = new Mach1PlatformType("Mach1PlatformUE");
  public final static Mach1PlatformType Mach1PlatformOfEasyCam = new Mach1PlatformType("Mach1PlatformOfEasyCam");
  public final static Mach1PlatformType Mach1PlatformAndroid = new Mach1PlatformType("Mach1PlatformAndroid");
  public final static Mach1PlatformType Mach1PlatformiOS = new Mach1PlatformType("Mach1PlatformiOS");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static Mach1PlatformType swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + Mach1PlatformType.class + " with value " + swigValue);
  }

  private Mach1PlatformType(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private Mach1PlatformType(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private Mach1PlatformType(String swigName, Mach1PlatformType swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static Mach1PlatformType[] swigValues = { Mach1PlatformDefault, Mach1PlatformUnity, Mach1PlatformUE, Mach1PlatformOfEasyCam, Mach1PlatformAndroid, Mach1PlatformiOS };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

