name: Build-Cocoapods

# run after tests are verified and the lib source files were edited
on:
  workflow_run:
    workflows: ["Test"]
    types:
      - completed

jobs:
  build:
    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v4
      with:
        lfs: true
        fetch-depth: 1

    - uses: actions/checkout@v4
      with:
        repository: mity/acutest
        path: libmach1spatial/deps/acutest

    - uses: actions/checkout@v4
      with:
        repository: g-truc/glm
        path: libmach1spatial/deps/glm

    - uses: actions/checkout@v4
      with:
        repository: zeux/pugixml
        path: libmach1spatial/deps/pugixml

    - uses: actions/checkout@v4
      with:
        repository: jimmiebergmann/mini-yaml
        path: libmach1spatial/deps/yaml

    - uses: actions/checkout@v4
      with:
        repository: nlohmann/json
        path: libmach1spatial/deps/nlohmann

    - uses: actions/checkout@v4
      with:
        repository: leetal/ios-cmake
        path: libmach1spatial/cmake/ios-cmake

    - name: Create dirs
      run: mkdir -p _builds/osx _builds/ios

    - name: Configure CMake (macos)
      run: cmake . -B_builds/osx -GXcode -DCMAKE_BUILD_TYPE=Release -DM1S_BUILD_EXAMPLES=OFF -DM1S_BUILD_SIGNAL_SUITE=OFF -DM1S_BUILD_TESTS=OFF -DBUILD_COCOAPODS_LIBS=ON -DCMAKE_TOOLCHAIN_FILE=libmach1spatial/cmake/ios-cmake/ios.toolchain.cmake -DPLATFORM=MAC_UNIVERSAL

    - name: Build (macos)
      shell: bash
      run: cmake --build _builds/osx --config Release

    - name: Install (macos)
      shell: bash
      run: cmake --install _builds/osx --config Release

    - name: Configure CMake (ios)
      run: cmake . -B_builds/ios -GXcode -DCMAKE_BUILD_TYPE=Release -DM1S_BUILD_EXAMPLES=OFF -DM1S_BUILD_SIGNAL_SUITE=OFF -DM1S_BUILD_TESTS=OFF -DBUILD_COCOAPODS_LIBS=ON -DCMAKE_TOOLCHAIN_FILE=libmach1spatial/cmake/ios-cmake/ios.toolchain.cmake -DPLATFORM=OS64COMBINED

    - name: Build (ios)
      shell: bash
      run: cmake --build _builds/ios --config Release

    - name: Install (ios)
      shell: bash
      run: cmake --install _builds/ios --config Release

    - name: Push to cocoapods submodule
      run: |
        cd $GITHUB_WORKSPACE/examples/mach1spatial-c/ios/Pod-Mach1SpatialAPI
        git config --global user.name "$(git log -n 1 --pretty=format:%an)"
        git config --global user.email "$(git log -n 1 --pretty=format:%ae)"
        git add .
        git commit -m "Update prebuilt libraries from CMake build"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
