name: Publish Pre-built Binaries
on:
  push:
    branches:
      - master
    paths:
      - 'mach1spatial-libs/**'

jobs:
  build:
    name: Publish pre-built library files
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Create archive of latest pre-built binaries
      run: zip mach1spatial-libs.zip ./mach1spatial-libs/* -r

    - name: Set outputs
      id: vars
      run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: mach1spatial-libs.zip
        asset_name: mach1spatial-libs.zip
        tag: ${{ steps.vars.outputs.sha_short }}
        overwrite: true
