name: Build-webjs

# run after tests are verified and the lib source files were edited
on:
  workflow_run:
    workflows: ["Test"]
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        lfs: true
        fetch-depth: 1
        persist-credentials: false # So that we can push with BOT_TOKEN, otherwise it doesn't trigger CI

    - uses: actions/checkout@v4
      with:
        repository: mity/acutest
        path: libmach1spatial/deps/acutest
        persist-credentials: false # So that we can push with BOT_TOKEN, otherwise it doesn't trigger CI

    - uses: actions/checkout@v4
      with:
        repository: g-truc/glm
        path: libmach1spatial/deps/glm
        persist-credentials: false # So that we can push with BOT_TOKEN, otherwise it doesn't trigger CI

    - uses: actions/checkout@v4
      with:
        repository: zeux/pugixml
        path: libmach1spatial/deps/pugixml
        persist-credentials: false # So that we can push with BOT_TOKEN, otherwise it doesn't trigger CI

    - uses: actions/checkout@v4
      with:
        repository: jimmiebergmann/mini-yaml
        path: libmach1spatial/deps/yaml
        persist-credentials: false # So that we can push with BOT_TOKEN, otherwise it doesn't trigger CI

    - uses: actions/checkout@v4
      with:
        repository: nlohmann/json
        path: libmach1spatial/deps/nlohmann
        persist-credentials: false # So that we can push with BOT_TOKEN, otherwise it doesn't trigger CI

    - uses: actions/checkout@v4
      with:
        repository: Mach1Studios/m1-web-spatialaudioplayer
        path: examples/mach1spatial-web/m1-web-spatialaudioplayer
        persist-credentials: false # So that we can push with BOT_TOKEN, otherwise it doesn't trigger CI

    - uses: actions/checkout@v4
      with:
        repository: Mach1Studios/NodeJS-Mach1Decode
        path: examples/mach1spatial-nodejs/mach1spatial-decode
        persist-credentials: false # So that we can push with BOT_TOKEN, otherwise it doesn't trigger CI

    - uses: actions/checkout@v4
      with:
        repository: Mach1Studios/NodeJS-Mach1Encode
        path: examples/mach1spatial-nodejs/mach1spatial-encode
        persist-credentials: false # So that we can push with BOT_TOKEN, otherwise it doesn't trigger CI

    - uses: actions/checkout@v4
      with:
        repository: Mach1Studios/NodeJS-Mach1Transcode
        path: examples/mach1spatial-nodejs/mach1spatial-transcode
        persist-credentials: false # So that we can push with BOT_TOKEN, otherwise it doesn't trigger CI

    - uses: mymindstorm/setup-emsdk@v14

    - name: Verify emscripten installation
      run: emcc -v

    - name: Generate JS via Emscripten
      run: make deploy-web

    - name: Commit to web js example
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "$(git log -n 1 --pretty=format:%ae)"
        git ls-files ./ | grep '\.wasm$' | xargs git add
        git ls-files ./ | grep '\.js$' | xargs git add
        git commit -m "Update prebuilt libraries from CMake build"

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}

    - name: Commit to m1-web-spatialaudioplayer example
      run: |
        cd $GITHUB_WORKSPACE/examples/mach1spatial-web/m1-web-spatialaudioplayer/js
        git config --global user.name "github-actions[bot]"
        git config --global user.email "$(git log -n 1 --pretty=format:%ae)"
        git add .
        git commit -m "Update prebuilt libraries from CMake build"

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        directory: examples/mach1spatial-web/m1-web-spatialaudioplayer
        repository: Mach1Studios/m1-web-spatialaudioplayer
        github_token: ${{ secrets.GITHUB_TOKEN }}

    - name: Commit to NodeJS decode example
      run: |
        cd $GITHUB_WORKSPACE/examples/mach1spatial-nodejs/mach1spatial-decode/lib
        git config --global user.name "github-actions[bot]"
        git config --global user.email "$(git log -n 1 --pretty=format:%ae)"
        git add .
        git commit -m "Update prebuilt libraries from CMake build"

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        directory: examples/mach1spatial-nodejs/mach1spatial-decode
        repository: Mach1Studios/NodeJS-Mach1Decode
        github_token: ${{ secrets.GITHUB_TOKEN }}

    - name: Commit to NodeJS encode example
      run: |
        cd $GITHUB_WORKSPACE/examples/mach1spatial-nodejs/mach1spatial-encode/lib
        git config --global user.name "github-actions[bot]"
        git config --global user.email "$(git log -n 1 --pretty=format:%ae)"
        git add .
        git commit -m "Update prebuilt libraries from CMake build"

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        directory: examples/mach1spatial-nodejs/mach1spatial-encode
        repository: Mach1Studios/NodeJS-Mach1Encode
        github_token: ${{ secrets.GITHUB_TOKEN }}

    - name: Commit to NodeJS transcode example
      run: |
        cd $GITHUB_WORKSPACE/examples/mach1spatial-nodejs/mach1spatial-transcode/lib
        git config --global user.name "github-actions[bot]"
        git config --global user.email "$(git log -n 1 --pretty=format:%ae)"
        git add .
        git commit -m "Update prebuilt libraries from CMake build"

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        directory: examples/mach1spatial-nodejs/mach1spatial-transcode
        repository: Mach1Studios/NodeJS-Mach1Transcode
        github_token: ${{ secrets.GITHUB_TOKEN }}
